### ISSUE TITLE
Launch link should include registration

### ISSUE THREAD

**Issue by fugu13** [davidpesce/moodle-mod_tincanlaunch#1]
Not including a registration UUID causes some rapid authoring packages to send invalid registrations under certain circumstances. Plus, sending it helps analysis tools do their job better.

**Comment by garemoko** [comment]
Any thoughts on how to decide what UUID to send? I don't want to reset it every time as that will mess up bookmarking, but presumably I do want a different one sometimes. Maybe for this next iteration I'll just have a fixed UUID for each user on each link.

**Comment by garemoko** [comment]
Perhaps I'll need to give the learner the option to load an old attempt or start a new one.

**Comment by garemoko** [comment]
**Cunning plan:** I'm going to store a list of registrations and some metadata in the state API on the LRS. That way the learner will have the same list of attempts to choose from no matter where they launch from.

**Comment by garemoko** [comment]
This is now resolved on the development branch so I'm closing the issue. I'll do a PR into master and release an new version sometime soon.

Also see https://twitter.com/mrdownes/status/376090451276623873
