### ISSUE TITLE
Change Actor in xAPI to be Assigned Moodle ID

### ISSUE THREAD

**Issue by maharlikans** [davidpesce/moodle-mod_tincanlaunch#107]
Hello, 

I hope you are well. I noted this in the readme: 

"With a little work, the plugin can be modified to use the Moodle account id instead."

I'm doing some work that requires that we don't use the actor's email address as an identifier, and instead keep them mostly anonymous with only the moodle user assigned id # as the base identifier. 

What files should I change to have this functionality? 

Best wishes,
Kyle

**Comment by garemoko** [comment]
Hi, 
I guess I need to update the readme. The plugin has had functionality for you to select how users are identified for a while - just change the settings in config. 

Andrew

**Comment by dwainbeck** [comment]
To change the identifier type for the user follow the instructions below;

When logged into Moodle, go to;
Site Administration
Plugins
Activity modules
Now select Tin Can Launch Link

This is where you can change the plugin's settings

Scroll down to 'Identify by email' to select whether to identify user by email. No check means identifying the user by the moodle user ID.
