### ISSUE TITLE
How to insert some other website score in to moodle

### ISSUE THREAD

**Issue by starrajendran** [davidpesce/moodle-mod_tincanlaunch#109]
HI,

I have one requirement. we created separate exam website using CORE PHP. it will show results. now manager wants to insert these results details in to MOODLE.
How to do ? please explain briefly

**Comment by garemoko** [comment]
Hi @starrajendran are you using this plugin and a learning record store to store the quiz results?

**Comment by starrajendran** [comment]
[
![exam](https://cloud.githubusercontent.com/assets/20186073/17700251/a3cfdfec-63e2-11e6-9aca-fbdb5493a5a4.png)
![moo](https://cloud.githubusercontent.com/assets/20186073/17700279/c726d63a-63e2-11e6-988e-9127bef07422.png)

](url)

see i want to insert score details in to moodle database. when we click end test button in third party website.

this is my requirement.

**Comment by garemoko** [comment]
I understand the requirement I think. 

Do you have a learning record store? If not, are you planning to get one?

**Comment by starrajendran** [comment]
no. i don't have now.

**Comment by garemoko** [comment]
Ok, so at a high level, steps you will need to take if you want to use this plugin to solve your requirements are:
1. Get an LRS
2. Customize the plugin to pull the score into Moodle's gradebook. I expect the code would be run from here: https://github.com/garemoko/moodle-mod_tincanlaunch/blob/master/completion_check.php 

Do you have developer(s) who could do that work? I'm happy to answer any specific questions they have about this work.
