### ISSUE TITLE
Does xapi plugin provide RESTful web servives

### ISSUE THREAD

**Issue by chandanch** [davidpesce/moodle-mod_tincanlaunch#110]
Hello currently I'm using tincan in my moodle system, I was wondering if this plugin provide RESTful API's for : 1. Authenticating the user  2. Getting the list of activities the user has completed. 3. Pushing the user experience on to the LRS. 4. Updating the user activities on to the LRS. I have mobile app which uses moodle RESTful API 's to get the enrolled courses etc. I'm planning to add the user analytics feature to it which contact the xapi plugin via a REST based API and get the Data is JSON or XML format.

**Comment by garemoko** [comment]
Hi, 

This plugin doesn't do anything like that. This plugin is for the launch of xapi content packages which are then tracked to a separate LRS.

If you are looking for a plugin that tracks Moodle activity via xAPI then try this one: https://moodle.org/plugins/logstore_xapi

**Comment by chandanch** [comment]
Thanks,  logstore plugin helped me to capture some of the logs. 👍
