### ISSUE TITLE
Error 500 when I launch courses containing Articulate quizzes (Moodle 3.1)

### ISSUE THREAD

**Issue by andicaragea** [davidpesce/moodle-mod_tincanlaunch#112]
I systematically encounter the error 500 ("Unable to connect to server"), in the middle of a course, when an (Articulate) quiz has to start. I have tested it in cloud.scorm.com and it works. It works also on a moodle 3.0 installation (on another server).

**Comment by garemoko** [comment]
Do you get any data in the LRS before the error? 

If no, then I expect it's a problem with your configuration settings. Please can you provide the following:
- Screenshot of your configuration settings
- Copy and paste of the endpoint, key and secret
- Copy and paste of the url when the course is launched. 

If yes, it's not a problem with this plugin but rather with your LRS or the content package. Still, that doesn't mean I can't help. 

Whether the answer is yes or no, it would still be useful to know the following:
- Which LRS (and version if relevant) you are using. I recommend you test against a few, including SCORM Cloud LRS. 
-  If you're using http or https for both the content and the LRS
- The full error message. You can get this by running the course in Chrome and [opening up the Network tab](https://www.google.co.uk/webhp?q=how%20to%20open%20network%20tab%20in%20chrome).

**Comment by andicaragea** [comment]
Thank you for promptitude!

I use Learning Locker as LRS (1.13.5 - last version). I use http on both LRS & LMS. 
It worked within Scorm Cloud, but I didn't try it as the endpoint LRS. (I shall try this in a few hours) 
1. Yes I get this in the LRS: 

Tester MOODLE launched http://6DmrgCxXfKx_course_id | 1 day ago (Tue, Oct 4, 2016 9:59 PM)

**BUT ... if the limit of time expires ... I get records like this:**

Tester MOODLE failed http://5b6BiqmC6AX_course_id | 23 hours ago (Wed, Oct 5, 2016 12:55 AM)
Tester MOODLE failed http://5b6BiqmC6AX_course_id/6RhVEyyhf1I2 | 23 hours ago (Wed, Oct 5, 2016 12:55 AM)
 avatar Tester MOODLE answered http://5b6BiqmC6AX_course_id/5nFS6jajgyo2/6YQei0cDp6F | 23 hours ago (Wed, Oct 5, 2016 12:55 AM)
 avatar Tester MOODLE experienced http://5b6BiqmC6AX_course_id/5nFS6jajgyo2 | 23 hours ago (Wed, Oct 5, 2016 12:50 AM)
 avatar Tester MOODLE experienced http://5b6BiqmC6AX_course_id/5ovibjrQOh3 | 23 hours ago (Wed, Oct 5, 2016 12:50 AM)
 avatar Tester MOODLE attempted http://5b6BiqmC6AX_course_id | 23 hours ago (Wed, Oct 5, 2016 12:50 AM)

Thank you again for your promptitude!

**Comment by andicaragea** [comment]
Hi,

I come with new information!

A. I have modified the document (it is only a quiz now) 

When the results page appears I get the 500 error message.

In LRS I've got only this statements ... even I've completed the quiz

Tester2 Test launched http://6DmrgCxXfKx_course_id | 4 minutes ago (Thu, Oct 6, 2016 4:16 AM)
 **avatar** Tester2 Test launched http://6DmrgCxXfKx_course_id | 5 minutes ago (Thu, Oct 6, 2016 4:15 AM) (avatar -?! what is this? )

**I've enabled the debugging mode and I get this when I launch the tin can content.:

**Notice: Undefined variable: registrationuuid in /home/xxxxxxxxx/public_html/xlrn/mod/tincanlaunch/locallib.php on line 220

Warning: Cannot modify header information - headers already sent by (output started at /home/xxxxxxxxx/public_html/xlrn/mod/tincanlaunch/locallib.php:220) in /home/xxxxxxxxxxx/public_html/xlrn/mod/tincanlaunch/launch.php on line 174 

**## SURPRISE!** After I have disabled the debugging it works!**

LRS:

Tester MOODLE passed http://6DmrgCxXfKx_course_id | 7 minutes ago (Thu, Oct 6, 2016 5:08 AM)
 avatar Tester MOODLE passed http://6DmrgCxXfKx_course_id/6RhVEyyhf1I | 7 minutes ago (Thu, Oct 6, 2016 5:08 AM)
 avatar Tester MOODLE answered http://6DmrgCxXfKx_course_id/5nFS6jajgyo/6YQei0cDp6F | 7 minutes ago (Thu, Oct 6, 2016 5:08 AM)
 avatar Tester MOODLE answered http://6DmrgCxXfKx_course_id/5nFS6jajgyo/6YQei0cDp6F | 7 minutes ago (Thu, Oct 6, 2016 5:08 AM)
 avatar Tester MOODLE experienced http://6DmrgCxXfKx_course_id/5nFS6jajgyo | 7 minutes ago (Thu, Oct 6, 2016 5:08 AM)
 avatar Tester MOODLE attempted | 7 minutes ago (Thu, Oct 6, 2016 5:07 AM)
 avatar Tester MOODLE launched http://6DmrgCxXfKx_course_id | 7 minutes ago (Thu, Oct 6, 2016 5:07 AM)
 avatar Tester MOODLE experienced http://6DmrgCxXfKx_course_id/5WjgibgHT0m | 7 minutes ago (Thu, Oct 6, 2016 5:07 AM)
Tester MOODLE passed http://6DmrgCxXfKx_course_id/6RhVEyyhf1I | 6 minutes ago (Thu, Oct 6, 2016 5:07 AM)
 avatar Tester MOODLE answered http://6DmrgCxXfKx_course_id/5nFS6jajgyo/6YQei0cDp6F | 7 minutes ago (Thu, Oct 6, 2016 5:06 AM)
 avatar Tester MOODLE experienced http://6DmrgCxXfKx_course_id/5nFS6jajgyo | 10 minutes ago (Thu, Oct 6, 2016 5:03 AM)
 avatar Tester MOODLE attempted | 10 minutes ago (Thu, Oct 6, 2016 5:03 AM)

**Comment by garemoko** [comment]
Ok, so firstly I've fixed the 'Undefined variable: registrationuuid' bug in this commit: https://github.com/garemoko/moodle-mod_tincanlaunch/commit/e7799fd82e533c95ba9df7b9e083f6c5b613b32d

It'll be in the next release but you can and should copy that into your code. 

Secondly your tests indicate that launch url being generated was bad ad you were getting no statements directly from the content package (the launched statement comes from Moodle). 

Thirdly, theres no reason why turning debugging on and off again would fix this so either its an intermittent problem or something else changed. Is it consistently working now? What about if you try a different user or different course? 

More of the information requested above, especially the Chrome network tab details of the error would be helpful in debugging this further. 

As you've said this is fixed I;m going to close the issue, however please re-open it if its not really fixed.

**Comment by andicaragea** [comment]
Thank you,

I've changed the code as in e7799fd.
I've got the same error 500 only in Firefox. But it works well in Chrome and
![firefox500error](https://cloud.githubusercontent.com/assets/5286249/19153069/9607e288-8bdd-11e6-989e-ad57c73b926f.png)
![llockerrecords](https://cloud.githubusercontent.com/assets/5286249/19153070/96125cf4-8bdd-11e6-9839-c1f03e62e79a.png)

 Edge. I attach two screenshots regarding the Firefox error.

**Comment by garemoko** [comment]
Can you get the "Antete" section full size and in its on window? 

Can you repeat it with a few different error codes? 

The cross origin error might be something you need to discuss with your host, although I have no clue why it would work with Chrome and Edge but have this error in Firefox; that is weird.

**Comment by andicaragea** [comment]
![headers raw-requesr-answer](https://cloud.githubusercontent.com/assets/5286249/19163521/00688e62-8c05-11e6-958f-adc38ae8362a.png)
![headers-answer](https://cloud.githubusercontent.com/assets/5286249/19163522/006af0a8-8c05-11e6-8575-a6abece5afcf.png)
![headers-details](https://cloud.githubusercontent.com/assets/5286249/19163520/0068d084-8c05-11e6-85cb-d89c0e1f3cea.png)

**Comment by garemoko** [comment]
Whats your activity id?

**Comment by andicaragea** [comment]
http://6DmrgCxXfKx_course_id

You can see the tincan.xml file and the course here: http://caragea.eu/1/3/

**Comment by garemoko** [comment]
That's what's causing at least one of the errors. Here's a detailed guide to activity ids: https://watershedlrs.zendesk.com/hc/en-us/articles/214880383-Get-the-Activity-Id-Right

Also check out this Storyline guide here: https://watershedlrs.zendesk.com/hc/en-us/articles/206275133-Storyline There's a section on activity ids and some other advice that might be helpful.

**Comment by andicaragea** [comment]
Thank you very much Andrew.
You are extremely kind!
