### ISSUE TITLE
Storyline 2 file error: Configuration Data is missing or incorrect

### ISSUE THREAD

**Issue by anthkris** [davidpesce/moodle-mod_tincanlaunch#113]
Howdy,
I'm testing this plugin with an installation of Moodle 3.1 and Learning Locker 1.13.5. It was working properly a couple of days ago. Today, I tried to edit some files in an attempt to get some javascript to load, but I've uninstalled and reinstalled twice now to undo my edits (including completely deleting the file from the mods folder) and, on clicking the link, nothing happens. No errors in the console or on the page. The page just shows the text of the description. When I try to access the Storyline 2 file based on the launch URL the plugin generates, I get the error "Configuration Data is missing or incorrect" but I've uploaded the same file into SCORM Cloud and it will open.

I don't know if this has anything to do with it but I thought I'd mention it. The other change I've made today is to get my LL instance working over HTTPS. I've update the LRS settings and am not seeing any errors related to that, either.

Any help much appreciated!

**Comment by garemoko** [comment]
Hi. 

Can you let me know the full url the course launches with?

Also please try to get error messages to maximum in your moodle's admin settings.

**Comment by anthkris** [comment]
Here's the link: http://knanthony.com/moodle/pluginfile.php/37/mod_tincanlaunch/content/story.html

I'm not sure what you mean by getting the error messages to maximum. Can you explain?

**Comment by garemoko** [comment]
Did you copy that link from your settings or from your web browser? Please can you copy it from the web browser?

Here's the Moodle help guide about errors: https://docs.moodle.org/31/en/Debugging 'DEVELOPER' is the setting that you want for the purposes of debugging. NONE is the setting that you want the rest of the time.

**Comment by anthkris** [comment]
Awesome! So here's the error from the debug settings being at Developer level:

```
Fatal error: Class 'TinCan\ErrorException' not found in /home/[mysite]/public_html/moodle/mod/tincanlaunch/TinCanPHP/src/RemoteLRS.php on line 130
```

Sorry for being so ignorant but I don't know how to get the link from the web browser since the course won't launch at all.

**Comment by anthkris** [comment]
I put a slash in line 130 as shown here: http://git.devspark.ru/y_alexander/tincan/commit/4017ae404afc9f9f8d817f90962653b243846a07

And now I get this:

```
Exception - fopen(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
```

Which suggests a problem with my self-signed certificate.

**Comment by anthkris** [comment]
Alright. I created a new Learning Locker that wasn't https. But now I'm getting different errors on the storyline page:

```
Notice: Undefined variable: registrationuuid in /home/[mysite]/public_html/moodle/mod/tincanlaunch/locallib.php on line 221

Warning: Cannot modify header information - headers already sent by (output started at /home/[mysite]/public_html/moodle/mod/tincanlaunch/locallib.php:221) in /home/[mysite]/public_html/moodle/mod/tincanlaunch/launch.php on line 174
```

Very confused at this point.

**Comment by garemoko** [comment]
Awesome. So you diagnosed and fixed the original issue. 

Now you're hitting a known issue with the Learning Locker integration in the current release  (I only test with Watershed LRS). That will be fixed in the next release. The fix code is here: https://github.com/garemoko/moodle-mod_tincanlaunch/commit/e7799fd82e533c95ba9df7b9e083f6c5b613b32d

**Comment by anthkris** [comment]
Thanks @garemoko It's working! Now I'm getting a 404 error for activities GET but I know that's not the plugin.

**Comment by garemoko** [comment]
404 is probably the appropriate error code since there will be no data on first launch. Where are you getting that error? You might just need to turn debugging errors back to NONE.
