### ISSUE TITLE
Private content

### ISSUE THREAD

**Issue by liviutarcovnicu** [davidpesce/moodle-mod_tincanlaunch#114]
Hi,
How can I launch private content with Moodle Launch? Is it possible?
If yes, what has an author to install and/or setup on his server for this?

**Comment by garemoko** [comment]
Hi

This plugin does not implement the ['launching private content' method as described here](https://github.com/RusticiSoftware/launch/blob/master/lms_lrs.md#private-content-access-and-tincan). Pull requests are welcome if you want to add this functionality. 

However if you upload a course package zip file, the content will be hosted privately on the Moodle server and only accessible to people who are logged in to Moodle. See https://github.com/garemoko/moodle-mod_tincanlaunch/blob/601bab77a42727ccd1cd178f37404db166fb101f/lib.php#L416

**Comment by liviutarcovnicu** [comment]
Thank you very much for this info

2016-10-17 13:58 GMT+03:00 Andrew Downes notifications@github.com:
