### ISSUE TITLE
MOODLE 3 Install - Fatal error: require_once(): Failed opening

### ISSUE THREAD

**Issue by nmcilree** [davidpesce/moodle-mod_tincanlaunch#116]
I get the following error when I install this mod on MOODLE 3.1.3 - sorry if this is not supposed to work in MOODLE 3 but I could not see any docs regarding this.

Fatal error: require_once(): Failed opening required '<site-path>/mod/tincanlaunch/TinCanPHP/autoload.php'

**Comment by nmcilree** [comment]
Sorry - my bad, found the project page showing only for 2.x

**Comment by garemoko** [comment]
You need to install from the plugins library: https://moodle.org/plugins/mod_tincanlaunch
