### ISSUE TITLE
Add new user profile field to xAPI statements

### ISSUE THREAD

**Issue by dwainbeck** [davidpesce/moodle-mod_tincanlaunch#117]
I have been receiving some help in regards to being able to add new fields to the tin can statements but so far the modifications I have made are still not adding the field to the statement.

So far I have learned that it is best practice to add new fields under "context" by the extensions object. 

I am using moodle as a LMS and I am sure that it is the Tin Can Launch Link that is sending the statements to the LRS and also pretty sure that it is the locallib.php file that prepares the statements.

I am wondering if when the statements are created only certain parts are parsed and accepted by the LRS(Learning Locker in my case), Or do I need to make changes in other areas(like another file).

Can anyone help with this please?

Here is my code below that I have edited in the locallib.php file

            "context" => array(
                "registration" => $registration_id,
                "contextActivities" => array(
                    "parent"  => array(
                        array(
                            "id" => $CFG->wwwroot.'/course/view.php?id='. $course->id,
                            "objectType" => "Activity",
                            "definition" => $parentDefinition
                        )
                    ),
                    "grouping" => array(
                        array(
                            "id" => $CFG->wwwroot,
                            "objectType" => "Activity"
                        )
                    ),
                    "extensions" => array(
                        "http://mysite.com/apps/xAPI/extensions/context/region" => "Region 21"
                    ),
                    "category"  => array(
                        array(
                            "id" => "https://moodle.org",
                            "objectType" => "Activity",
                            "definition" => array (
                                "type" => "http://id.tincanapi.com/activitytype/source"
                            )
                        )
                    )
                ),
                "language" => tincanlaunch_get_moodle_langauge()
            ),

**Comment by dwainbeck** [comment]
I have been receiving some help in regards to being able to add new fields to the tin can statements but so far the modifications I have made are still not adding the field to the statement.

So far I have learned that it is best practice to add new fields under "context" by the extensions object.

I am using moodle as a LMS and I am sure that it is the Tin Can Launch Link that is sending the statements to the LRS and also pretty sure that it is the locallib.php file that prepares the statements.

I am wondering if when the statements are created only certain parts are parsed and accepted by the LRS(Learning Locker in my case), Or do I need to make changes in other areas(like another file).

Can anyone help with this please?

Here is my code below that I have edited in the locallib.php file

        "context" => array(
            "registration" => $registration_id,
            "contextActivities" => array(
                "parent"  => array(
                    array(
                        "id" => $CFG->wwwroot.'/course/view.php?id='. $course->id,
                        "objectType" => "Activity",
                        "definition" => $parentDefinition
                    )
                ),
                "grouping" => array(
                    array(
                        "id" => $CFG->wwwroot,
                        "objectType" => "Activity"
                    )
                ),
                "extensions" => array(
                    "http://mysite.com/apps/xAPI/extensions/context/region" => "Region 21"
                ),
                "category"  => array(
                    array(
                        "id" => "https://moodle.org",
                        "objectType" => "Activity",
                        "definition" => array (
                            "type" => "http://id.tincanapi.com/activitytype/source"
                        )
                    )
                )
            ),
            "language" => tincanlaunch_get_moodle_langauge()
        ),

**Comment by garemoko** [comment]
Can you share the full statement as it appears in learning locker?

**Comment by dwainbeck** [comment]
{
    "version": "1.0.0",
    "actor": {
        "objectType": "Agent",
        "name": "LMS User",
        "mbox": "mailto:admin@email.com"
    },
    "verb": {
        "id": "http://adlnet.gov/expapi/verbs/experienced"
    },
    "context": {
        "registration": "81203947-e736-4f12-9b04-999d4348233d",
        "contextActivities": {
            "grouping": [
                {
                    "objectType": "Activity",
                    "id": "http://unique_url"
                }
            ],
            "parent": [
                {
                    "objectType": "Activity",
                    "id": "http://unique_url2"
                }
            ]
        }
    },
    "object": {
        "objectType": "Activity",
        "id": "http://unique_url/6Jv8029UFie",
        "definition": {
            "name": {
                "und": "Audio Controls"
            },
            "type": "http://adlnet.gov/expapi/activities/module",
            "description": {
                "und": "Audio Controls"
            }
        }
    },
    "id": "f6137dc1-4fc9-4275-bb9e-ac475e01cdd1",
    "authority": {
        "objectType": "Agent",
        "name": "API Client",
        "mbox": "mailto:hello@learninglocker.net"
    },
    "stored": "2016-12-06T16:37:08.162200+00:00",
    "timestamp": "2016-12-06T16:37:08.162200+00:00"
}

No matter the changes I make in locallib.php the new field is not added.

**Comment by garemoko** [comment]
Do you have the statement with the verb "launched"?

**Comment by dwainbeck** [comment]
Yes I do;

{
    "version": "1.0.0",
    "id": "962bea11-322a-49bf-87f4-914849a313ba",
    "actor": {
        "objectType": "Agent",
        "name": "LMS User",
        "mbox": "mailto:admin@email.com"
    },
    "verb": {
        "id": "http://adlnet.gov/expapi/verbs/launched",
        "display": {
            "en-US": "launched"
        }
    },
    "context": {
        "registration": "81203947-e736-4f12-9b04-999d4348233d",
        "contextActivities": {
            "category": [
                {
                    "objectType": "Activity",
                    "id": "https://moodle.org",
                    "definition": {
                        "type": "http://id.tincanapi.com/activitytype/source"
                    }
                }
            ],
            "parent": [
                {
                    "objectType": "Activity",
                    "id": "http://www.myvirtualcareercenter.com/course/view.php?id=91",
                    "definition": {
                        "name": {
                            "en-US": " New Course"
                        }
                    }
                }
            ],
            "grouping": [
                {
                    "objectType": "Activity",
                    "id": "http://www.mysite.com"
                }
            ]
        },
        "language": "en-US"
    },
    "timestamp": "2016-12-06T12:56:09-05:00",
    "object": {
        "objectType": "Activity",
        "id": "http://unique_url"
    },
    "authority": {
        "objectType": "Agent",
        "name": "New Client",
        "mbox": "mailto:hello@learninglocker.net"
    },
    "stored": "2016-12-06T17:56:10.018200+00:00"
}

**Comment by garemoko** [comment]
Interesting. Can you var_dump both $statement and $response at this line and tell me what you get? https://github.com/garemoko/moodle-mod_tincanlaunch/blob/master/locallib.php#L115

Can you also try with another LRS and see if you get an error there?

Make sure you have debugging set to maximum so that this line triggers: https://github.com/garemoko/moodle-mod_tincanlaunch/blob/601bab77a42727ccd1cd178f37404db166fb101f/launch.php#L143

**Comment by dwainbeck** [comment]
Hi Andrew thanks for all the help, I am now making some headway. With the help of Brian Miller from tincanapi.com he pointed that I inadvertently had the "extensions" object under contextActivities. So I just moved it up one level like in the code you had sent me(If I folowed your instructions properly I would have worked), now the new field is added to the statements that has the verb launched.


            "context" => array(
                "registration" => $registration_id,
                "extensions" => array(
                    "http://mysite.com/vccapps/xAPI/extensions/context/region" => $region
                ),
                "contextActivities" => array(
                    "parent"  => array(
                        array(
                            "id" => $CFG->wwwroot.'/course/view.php?id='. $course->id,
                            "objectType" => "Activity",
                            "definition" => $parentDefinition
                        )
                    ),
                    "grouping" => array(
                        array(
                            "id" => $CFG->wwwroot,
                            "objectType" => "Activity"
                        )
                    ),
                    "category"  => array(
                        array(
                            "id" => "https://moodle.org",
                            "objectType" => "Activity",
                            "definition" => array (
                                "type" => "http://id.tincanapi.com/activitytype/source"
                            )
                        )
                    )
                ),
                "language" => tincanlaunch_get_moodle_langauge()
            ),

Issue now is that only the statements with the "launched" verd gets the new fields. Any idea on how I can get the other verbs to get the new field?

**Comment by garemoko** [comment]
Those statements come from whatever it is you are launching so you would need to make the changes there.
