### ISSUE TITLE
disable/hide completed registrations

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-mod_tincanlaunch#121]
As an additional option under Module Behavior, add a setting that will either show, disable or hide registrations that have been completed. This can be achieved by fetching statements to check for completion under each un-completed registration when the course loads and by adding a complete/uncomplete flag to each registration. This check should NOT take expiry dates into account since a new registration should be used when the course is re-taken. 

![image](https://cloud.githubusercontent.com/assets/1363163/21098294/6ae620a8-c060-11e6-884d-bc2ea4881b55.png)

**Comment by davidpesce** [comment]
Resolved in the current version.
