### ISSUE TITLE
Add ability to add custom profile fields to agent profile

### ISSUE THREAD

**Issue by davidpesce** [davidpesce/moodle-mod_tincanlaunch#129]
I have this need and currently have it hardcoded. Would like to see it as an option in the admin settings. 

If you see a need/benefit from this, I'll add it to my todo list.

**Comment by garemoko** [comment]
This is something that people ask about a bit, although I imagine if we implemented this here, then they still wouldn't be able to do anything with the data in the agent profile. 

The approach we take with this at Watershed is to push this data via a separate api.

**Comment by garemoko** [comment]
See https://github.com/WatershedLRS/moodle-report_watershed

**Comment by garemoko** [comment]
Not going to implement this unless somebody contributes a PR.
