### ISSUE TITLE
(MySQL 5.7) Missing field value 'tincanlaunchid' in database write

### ISSUE THREAD

**Issue by thepurpleblob** [davidpesce/moodle-mod_tincanlaunch#130]
```
Debug info: Field 'tincanlaunchid' doesn't have a default value
INSERT INTO mdl_tincanlaunch_lrs (lrsendpoint,lrsauthentication,customacchp,useactoremail,lrsduration,lrslogin,lrspass) VALUES(?,?,?,?,?,?,?)
[array (
  0 => '/',
  1 => '1',
  2 => '',
  3 => '1',
  4 => '9000',
  5 => '',
  6 => '',
)]
Error code: dmlwriteexception
Stack trace: 
line 477 of /lib/dml/moodle_database.php: dml_write_exception thrown
line 1172 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
line 1218 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->insert_record_raw()
line 139 of /mod/tincanlaunch/lib.php: call to mysqli_native_moodle_database->insert_record()
line 571 of /course/modlib.php: call to tincanlaunch_update_instance()
line 273 of /course/modedit.php: call to update_moduleinfo()
```

Looking at the code around function tincanlaunch_build_lrs_settings()  it doesn't appear to ever set that field. MySQL 5.7 doesn't like this sort of thing and the rest of Moodle works fine with 5.7.

Version 1.4 of the plugin on Moodle 3.1.3

**Comment by garemoko** [comment]
Thanks for reporting. Where are you seeing this error message?

Again, PRs are always welcome.

**Comment by thepurpleblob** [comment]
When I try to save the activity settings page. Quite possibly you don't use that field for anything. Versions of MySQL <5.7 won't care, but 5.7 is much fussier. You *have* to supply a value when creating a record for any fields that don't have a default defined.

**Comment by garemoko** [comment]
That field should be the instance id of the module the settings are being saved for. It should never be blank, so the bug isn't that it doesn't have a default but that it's not being set. I have two records in my local Moodle database (running the latest version of this plugin) both of which have that field completed. 

Does the error occur only with you are setting the LRS settings at the instance level or all of the time?

**Comment by thepurpleblob** [comment]
If you look at (in lib.php) function tincanlaunch_build_lrs_settings, it definitely does not set tincanlaunchid (from $tincanlaunch->instance I suppose).

The function that uses that 'tincanlaunch_update_instance' decides to insert a new record but that never sets it either. So on the shaky basis of a visual inspection, this bit of code creates the record without that field set. 

However, much further down in 'function tincanlaunch_settings' a record can also be inserted in this table. However, this time the tincanlaunchid *is* set. I'm unsure which of these functions will normally create the record but the earlier one does look wrong (to me).

**Comment by garemoko** [comment]
I assume both bits of code must run in different scenarios given that you hit that error and I haven't.

**Comment by garemoko** [comment]
Ok, I see, that later bit of code specifically relates to the watershed LRS integration so if you're using another LRS it will never run. 

So you need to add a line of code on 173ish of lib.php like: 

```
$tincanlaunchlrs->tincanlaunchid = $tincanlaunch->instance;
```

Looking at the code, line 124 is quite weird. I don't know why we don't just use `$tincanlaunch->instance` consistently throughout lib.php instead of `$tincanlaunch->id`.

**Comment by MartinSandberg** [comment]
Thanks... adding the code from that last comment makes it work.

**Comment by garemoko** [comment]
Great! PRs welcome!

**Comment by garemoko** [comment]
Fixed in master, Will be in next release.
