### ISSUE TITLE
Missing namespace \ in mod/tincanlaunch/TinCanPHP/src/RemoteLRS.php

### ISSUE THREAD

**Issue by thepurpleblob** [davidpesce/moodle-mod_tincanlaunch#131]
If you fail to specify a working LRS, this error is generated...

```
Fatal error: Class 'TinCan\ErrorException' not found in /var/www/html/moodle31/mod/tincanlaunch/TinCanPHP/src/RemoteLRS.php on line 130
```
This seems to be because there is a missing backslash in front of 'ErrorException' on line 130. 

Even if that's fixed the resulting error is pretty scary as getting the LRS setting wrong (or not setting at all) is pretty likely.

**Comment by garemoko** [comment]
Thanks for reporting. Pull requests are always welcome to fix things like this. Get your face on the contributors list since you've already identified the fix! :-)

**Comment by thepurpleblob** [comment]
Ok... leave it with me :)

**Comment by thepurpleblob** [comment]
This was fixed in TinCanPHP some time ago...

https://github.com/RusticiSoftware/TinCanPHP/commit/4017ae404afc9f9f8d817f90962653b243846a07

I suppose the latest version needs integrated with the plugin.

**Comment by garemoko** [comment]
Ok, yes. We already have that version of TinCanPHP in the master branch of this repo, so this will be fixed in the next release. 

Did you also want to address: "Even if that's fixed the resulting error is pretty scary as getting the LRS setting wrong (or not setting at all) is pretty likely."?

**Comment by garemoko** [comment]
^^ Because better errors is an enhancement

**Comment by garemoko** [comment]
Actually, I'm closing this, I'd love to have more validation but it's nowhere near a priority compared to having a plugin that works without requiring code changes by the implementer.
