### ISSUE TITLE
Upgrading Moodle 2.7>3.1: Table "tincanlaunch_lrs" does not exist

### ISSUE THREAD

**Issue by mlhamilton** [davidpesce/moodle-mod_tincanlaunch#136]
Hey Andrew (long time!),

I'm upgrading our install of Moodle and your old tincanlaunch plugin (2014072300) to the new plugin (2016122702). Hoping to do this without having to uninstall/reinstall the plugin (along with all instances of tincan in our moodle) as you suggest in your README file.

After removing the old mod/tincanlaunch folder and cloning the current version from github, our tincan links complain: 
![capture](https://cloud.githubusercontent.com/assets/13615236/26221253/b60c57ec-3bca-11e7-8280-d0ffc525d679.JPG)

Hope that screenshot shows up, but if not here's the text:
moodle/mod/tincanlaunch/view.php?id=126

Table "tincanlaunch_lrs" does not exist

More information about this error

×Debug info: 
Error code: ddltablenotexist
×Stack trace:
line 645 of /lib/dml/moodle_database.php: dml_exception thrown
line 1501 of /lib/dml/moodle_database.php: call to moodle_database->where_clause()
line 895 of /mod/tincanlaunch/lib.php: call to moodle_database->get_record()
line 370 of /mod/tincanlaunch/locallib.php: call to tincanlaunch_settings()
line 100 of /mod/tincanlaunch/view.php: call to tincanlaunch_get_global_parameters_and_get_state()

**Comment by mlhamilton** [comment]
Thinking about it some more, clearly the upgrade script didn't create the tincanlaunch_lrs table (verified in the db). Any idea on how I create this manually? Any concerns that the upgrade script didn't create other things necessary to this plugin?

Could it be that I skipped a version of tincanlaunch that would have created this table?

**Comment by garemoko** [comment]
@mlhamilton I think what you are hitting here is that we haven't heavily tested the upgrade process Looking at the [upgrade script](https://github.com/garemoko/moodle-mod_tincanlaunch/blob/master/db/upgrade.php), it looks like that table should get created. I'm not sure why it didn't in your case. 

I think you have a couple of options:
1. Fix the upgrade script and re-do your upgrade. 
2. Fix the database yourself. 

Option 1 is best, option 2 is probably faster. 

To fix the database yourself, you could install the plugin from scratch on a separate Moodle and then edit the database on your real Moodle to match. Make sure you take a useable backup of your database before doing this. 

I hope that helps. Sorry it's not as straightforward as it should be.

**Comment by mlhamilton** [comment]
Thanks for the help (all the way back to our time with Epic)! 

Just want to be clear on the process:

To re-run the upgrade script once we've made changes, can I just use `php upgrade.php` from the command line? I've tried it, but doesn't seem to affect the db.

When looking at the version checks on the upgrade script, is the script checking our version of Moodle, or the version of the tincanlaunch plugin? Is there a way to know the difference?

Thanks again!

**Comment by garemoko** [comment]
I've never tried running the upgrade from cpmmand line so I'm not sure. I don't see why that wouldn't work though. 

The version checks should be the plugin version.

**Comment by mlhamilton** [comment]
Is there any chance you might fix this bug in the upgrade script (in case other's are also doing a 2.7-3.1 upgrade)?

**Comment by garemoko** [comment]
I currently have no plans to work on this plugin. However, if you submit a PR and get somebody else to review it and confirm it works, I will merge it.
