### ISSUE TITLE
No completion tick mark: Moodle - Storyline - Learning Locker

### ISSUE THREAD

**Issue by GoranFuru** [davidpesce/moodle-mod_tincanlaunch#138]
Hi,
We have an issue with the completion tick mark in Moodle. When using the "GolfExample_TCAPI" it works as expected but when using Storyline (A360) we don't get any completion in Moodle.
**Case:** 
Moodle Cron is set to 1 minute
Storyline course published as Tin Can.
![sl_pub](https://user-images.githubusercontent.com/29913663/27855110-9155f5d8-6169-11e7-94f5-69ce23a425fa.PNG)

Here's the tincan.xml after publishing:

![tincan_xml](https://user-images.githubusercontent.com/29913663/27856024-f0f8a3b6-616c-11e7-884f-a101f871f206.PNG)

The zip is uploaded in Moodle Tincan Launch link. And the Launch URL & Activity ID is defined automatically from the tincan.xml.
![launch_link_1](https://user-images.githubusercontent.com/29913663/27855479-f44791d2-616a-11e7-8ef0-a12aa9c1daa3.PNG)
![launch_link_2](https://user-images.githubusercontent.com/29913663/27855493-fa8f8de2-616a-11e7-90f4-862916d84307.PNG)
![launch_link_3](https://user-images.githubusercontent.com/29913663/27855502-000342f0-616b-11e7-9efc-742028d44263.PNG)

Launching and completing the course sends these statements to Learning Locker LRS ending up with completed:
![statements_1](https://user-images.githubusercontent.com/29913663/27855673-a68725f6-616b-11e7-884c-c0d829ec530a.PNG)
Here's the details in the launched, attempted and completed statements.
{
    "version": "1.0.0",
    "id": "a28ad40c-b1e6-4fd2-8fc5-a6a25e8cfbd8",
    "actor": {
        "objectType": "Agent",
        "name": "Elev Furu",
        "mbox": "mailto:goran.furu@gmail.com"
    },
    "verb": {
        "id": "http://adlnet.gov/expapi/verbs/launched",
        "display": {
            "en-US": "launched"
        }
    },
    "context": {
        "registration": "3f171709-89cc-45a1-a8ab-0d17edc0d8aa",
        "contextActivities": {
            "category": [
                {
                    "objectType": "Activity",
                    "id": "https://moodle.org",
                    "definition": {
                        "type": "http://id.tincanapi.com/activitytype/source"
                    }
                }
            ],
            "parent": [
                {
                    "objectType": "Activity",
                    "id": "http://demony.maincon.se/course/view.php?id=11",
                    "definition": {
                        "name": {
                            "en-US": "Sandbox"
                        },
                        "description": {
                            "en-US": "<p>Course summary text...</p>"
                        }
                    }
                }
            ],
            "grouping": [
                {
                    "objectType": "Activity",
                    "id": "http://demony.maincon.se"
                }
            ]
        },
        "language": "sv"
    },
    "timestamp": "2017-07-05T10:17:47+02:00",
    "object": {
        "objectType": "Activity",
        "id": "http://maincon.se/courses/xapi-2"
    },
    "authority": {
        "objectType": "Agent",
        "name": "New Client",
        "mbox": "mailto:hello@learninglocker.net"
    },
    "stored": "2017-07-05T08:17:47.882400+00:00"
}

------------------------------------------------------------------

{
    "version": "1.0.0",
    "id": "d462bc46-8b1b-4419-a32a-f44bea129853",
    "timestamp": "2017-07-05T08:17:51.062Z",
    "actor": {
        "objectType": "Agent",
        "mbox": "mailto:goran.furu@gmail.com",
        "name": "Elev Furu"
    },
    "verb": {
        "id": "http://adlnet.gov/expapi/verbs/attempted",
        "display": {
            "en-US": "attempted"
        }
    },
    "result": {
        "completion": false
    },
    "context": {
        "registration": "3f171709-89cc-45a1-a8ab-0d17edc0d8aa",
        "contextActivities": {
            "parent": [
                {
                    "objectType": "Activity",
                    "id": "http://"
                }
            ],
            "grouping": [
                {
                    "objectType": "Activity",
                    "id": "http://"
                }
            ]
        }
    },
    "object": {
        "objectType": "Activity",
        "id": "http://",
        "definition": {
            "type": "http://adlnet.gov/expapi/activities/course",
            "name": {
                "und": "xapi-2"
            },
            "description": {
                "und": ""
            }
        }
    },
    "authority": {
        "objectType": "Agent",
        "name": "API Client",
        "mbox": "mailto:hello@learninglocker.net"
    },
    "stored": "2017-07-05T08:17:52.139100+00:00"
}

-----------------------------------------------------------------
{
    "version": "1.0.0",
    "id": "85299ab3-b6d4-4cd9-ab82-45f9252f83fb",
    "timestamp": "2017-07-05T08:18:02.458Z",
    "actor": {
        "objectType": "Agent",
        "mbox": "mailto:goran.furu@gmail.com",
        "name": "Elev Furu"
    },
    "verb": {
        "id": "http://adlnet.gov/expapi/verbs/completed",
        "display": {
            "en-US": "completed"
        }
    },
    "result": {
        "duration": "PT11.398S",
        "extensions": {
            "http:///viewcount": 4
        },
        "completion": true
    },
    "context": {
        "registration": "3f171709-89cc-45a1-a8ab-0d17edc0d8aa",
        "contextActivities": {
            "parent": [
                {
                    "objectType": "Activity",
                    "id": "http://"
                }
            ],
            "grouping": [
                {
                    "objectType": "Activity",
                    "id": "http://"
                }
            ]
        }
    },
    "object": {
        "objectType": "Activity",
        "id": "http://",
        "definition": {
            "type": "http://adlnet.gov/expapi/activities/course",
            "name": {
                "und": "xapi-2"
            },
            "description": {
                "und": ""
            }
        }
    },
    "authority": {
        "objectType": "Agent",
        "name": "API Client",
        "mbox": "mailto:hello@learninglocker.net"
    },
    "stored": "2017-07-05T08:18:04.402000+00:00"
}

----------------------------------------------------------------------------------

The result in Moodle - No completion tick mark. (As you can see, the same methodology actually works with the Golf course).

![no_tick_mark_moodle](https://user-images.githubusercontent.com/29913663/27855918-8fcc2540-616c-11e7-943c-e7b474ca34f6.PNG)

**Comment by garemoko** [comment]
Thanks for all the detail. 

The problem is that the object id in your completed statement is "http://" whereas Moodle is looking for "http://maincon.se/courses/xapi-2". This issue will cause you a lot more problems when you come to report on the data too. 

Firstly, this seems like an xAPI conformance issue with learning locker because it should be rejecting "http://" as an invalid activity id. 

Second, either you didn't save the Storyline configuration or there is a bug in Storyline 360. Make sure you saved that identifier configuration and republish the course. If the object.id property continues to be "http://", then I recommend logging a bug with Articulate and using the latest version of Storyline 2 instead until the bug is resolved. 

If you get the statements fixed to use the correct object id and the completion issue persists, please open a new issue providing all the same (but updated) information again. 

![image](https://user-images.githubusercontent.com/1363163/27856663-a96fbf26-6166-11e7-94bb-8b383a2c7124.png)
