### ISSUE TITLE
Type mismatch when mod_tincan_lauch is associate to logstore_xapi

### ISSUE THREAD

**Issue by deedey** [davidpesce/moodle-mod_tincanlaunch#139]
Hi Andrew,
I find that when a mod_tincan_launch activity is launched while logstore_xapi is activated, there is a problem in a proxy server context.
I obtain an error like that:
**_Exception : Request failed: fopen(http://lrs.annulab.com/xapi/activities/state?activityId=6BLyVHKgcFE_course_id&agent=%7B%22objectType%22%3A%22Agent%22%2C%22name%22%3A%22Dey%20Bendifallah%22%2C%22mbox%22%3A%22mailto%3Ad.bendifallah%40gmail.com%22%7D&stateId=http%3A%2F%2Ftincanapi.co.uk%2Fstateapikeys%2Fregistrations): failed to open stream: Connection refused_**
This problem is related to the persistent call to proxy configuration by logstore_xapi.
To overcome this, it was necessary to ignore this aspect and comment three lines ( 164-166) in the "admin / tool / log / store / xapi / classes / log / store.php" script here :
         **_If (! Empty ($ CFG-> proxyhost)) {
           $ Remote_lrs-> setProxy (. $ CFG-> proxyhost '' $ CFG-> proxyport.);
         }_**
And set the proxy configuration to "moodle / admin / tool / log / store / xapi / vendor / rusticisoftware / tincan / src / remoteLRS.php"
'Proxy' => '192.168.100.241:8080',
With this operation, everything is work fine.
Is it possible to configure the proxy in the same way in logstore_xapi as in mod_tincanlaunch so that these two plugins can work together on the same moodle?

**Comment by garemoko** [comment]
I'm confused - I don't think this plugin has specific support for proxies. Are you using a modified version? If not, can you include some screenshots to illustrate what you're talking about?
