### ISSUE TITLE
Authoring tools supported?

### ISSUE THREAD

**Issue by alishahrazad** [davidpesce/moodle-mod_tincanlaunch#14]
Hi Andrew, does your plugin support Storyline and Captivate courses only or do others like Lectora and iSpring, etc work as well? Is the plugin ready for public use? Thanks!

**Comment by garemoko** [comment]
Hi Ali,
This plugin will work with any Tin Can content that implements the launch method mentioned in the read me file.

I'd say it's ready to use but be sure to test it fully and understand the level of security provided by basic authentication.

Andrew

Ali Shahrazad notifications@github.com wrote:

Hi Andrew, does your plugin support Storyline and Captivate courses only or do others like Lectora and iSpring, etc work as well? Is the plugin ready for public use? Thanks!

---

Reply to this email directly or view it on GitHub:
https://github.com/garemoko/moodle-mod_tincanlaunch/issues/14

**Comment by alishahrazad** [comment]
Ok, got it. Thanks Andrew.
