### ISSUE TITLE
401 error when creating watershed credentials on view.php

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-mod_tincanlaunch#141]
![image](https://user-images.githubusercontent.com/1363163/30326723-5b69f486-97c1-11e7-80e3-3ac1eb153001.png)

What's happening is that when trying to create credentials that will have a particular key and secret, the plugin is using those credentials that don't exist yet, rather than the api credentials. 

The issue appears to be here: https://github.com/garemoko/moodle-mod_tincanlaunch/blob/master/lib.php#L919-L920 But it needs more digging and testing. 

It's also worth noting that the function [tincanlaunch_build_lrs_settings](https://github.com/garemoko/moodle-mod_tincanlaunch/blob/master/lib.php#L163) appears to work. It's not clear why we're not just re-using that function; seems like we should.

**Comment by harlows** [comment]
I'm getting exactly this issue when trying to create a Tin Can Launch activity in Moodle 3.3.

**Comment by MartinSandberg** [comment]
I am also getting 401, unathorized when trying to connect to Learning Locker.

Same settings work fine with the logstore xAPI plugin.

Using Totara 10 (Moodle 3.2.4)

**Comment by garemoko** [comment]
@harlows does it work if you set the LRS integration to "none"?

@MartinSandberg Learning locker will be unaffected by this issue. Sounds like you are having a different issue. Please log a separate issue and provide screenshots.

**Comment by garemoko** [comment]
Related: https://github.com/garemoko/moodle-mod_tincanlaunch/issues/142

So a lot of this will need re-working anyway.

**Comment by harlows** [comment]
Changing LRS integration from Watershed to none allows me to create the activity, but then "The Learning Record Store is not available." As I guess, you might expect. I'll try with details hardcoded into the Activity.

**Comment by harlows** [comment]
Just discovered that if (I had read the instructions correctly and) I configure the Activity Provider with API Access enabled, the activity saves, but on launching returns:
`tincanlaunch/Failed to create Watershed Activity Provider. Status: 401. Response: {"message":"HTTP 401 Unauthorized","status":401}`

**Comment by harlows** [comment]
Further investigation suggests that the lack of an Activity ID in tincan.xml may be confounding the issue. Adding an Activity ID and then re-uploading the zip file allows me to get to "Start New Registration", but Watershed then rejects the statement with:
`Neither If-Match nor If-None-Match headers were set, please check the current state of the resource and set the If-Match header with the current ETag.`
Maybe it's an issue with the Activity format rather than the plugin?

**Comment by garemoko** [comment]
@harlows I'm afraid you're hitting separate bugs due to this repo needing a little love. 

1. The activity provider was not configured correctly. This is user error :-) and sounds like its now fixed. 

2. The 401 error (this issue). Interesting that adding the activity id in tincan.xml fixed this. I'm surprised that's the case because it should be unrelated. Maybe you did something else while testing and didn't realize it. 

3. The etag issue. That's actually an issue in TinCanPHP. See https://github.com/garemoko/moodle-mod_tincanlaunch/issues/140 for the fix.

**Comment by harlows** [comment]
In the meantime, as a workaround, I have found that setting SCORM Cloud as the Endpoint with LRS integration set to "None" and then forwarding statements from there into Watershed LRS works.

**Comment by garemoko** [comment]
Thanks @harlows. I suspect what's happening here is that maybe Cloud doesn't have as tight validation as Watershed just now and that's why this bug is getting ignored. Just be aware that without the TinCanPHP fix, an update to Cloud to improve validation could break your prototype.

**Comment by harlows** [comment]
@garemoko TBH I wasn't exactly sure how implement the TinCanPHP etag fix. I tried replacing the TinCanPHP folder in my moodle/mod/tincanlaunch with [the master branch](https://github.com/RusticiSoftware/TinCanPHP), but didn't seem to fix anything. Is that because your changes haven't been merged yet?

**Comment by garemoko** [comment]
Yes. You need to edit your RemoteLRS.php file directly https://github.com/RusticiSoftware/TinCanPHP/pull/90/files

**Comment by sumitnegi933** [comment]
@garemoko I am getting the same error with watershed integration, I am using Moodle3.3+. What exactly needs to be done at Moodle or LRS end to fix this?
Thanks

**Comment by sumitnegi933** [comment]
Fixed, you need to enable API and LRS access in activity provider at Watershed end

**Comment by garemoko** [comment]
Closing this because when i address #142 this code will be replaced.
