### ISSUE TITLE
TINCAN - Why can't I resume my tincan videos?

### ISSUE THREAD

**Issue by tjr007ma** [davidpesce/moodle-mod_tincanlaunch#143]
Hi everyone,

I am creating tin can session in moodle. When I play the tin can video, it plays fine, but when I leave the course and comes back, it never resumes where I left off. I have checked on my tin can authoring tool configuration and I have selected to resume play.

If I do the in SCORM it works fine.

any thoughts?

**Comment by garemoko** [comment]
What's the authoring tool? How does it work? is it storing anything in the document apis? Are you getting an errors?

**Comment by tjr007ma** [comment]
We are using Articulate 360.

**Comment by garemoko** [comment]
I've never tested with Articulate 360 myself. Have you tried the video on SCORM Cloud? have you posted on the Storyline forums? Could you share the video package here?

**Comment by tjr007ma** [comment]
Sorry Andrew, it is Articulate Sotryline 2, there is no errors at all. If I
save as SCORM file, it works fine. let me see if I get a small video
package.

**Comment by tjr007ma** [comment]
here is the file that plays, but it doesn't resume.

**Comment by tjr007ma** [comment]
sorry gmail is not allowing to send the file. let me find another way.

**Comment by tjr007ma** [comment]
[TinCanTest.zip](https://github.com/garemoko/moodle-mod_tincanlaunch/files/1450640/TinCanTest.zip)

**Comment by tjr007ma** [comment]
there it is.

**Comment by tjr007ma** [comment]
I've narrowed the issue down to TinCan. If I turn TinCan off in the story.html file by changing

var g_bTinCan = true; to var g_bTinCan = false;
The course resumes as it should. But since TinCan is off, it doesn't post any statements to my LMS.

**Comment by garemoko** [comment]
Sorry i never got to look at this package. If it's still an issue, feel free to email me andrew.downes@watershedlrs.com

Since this issue does not relate to the plugin, I'm closing it.
