### ISSUE TITLE
Rename "Learning Locker" Integration to "Learning Locker 1"

### ISSUE THREAD

**Issue by MartinSandberg** [davidpesce/moodle-mod_tincanlaunch#144]
Trying to use this plugin with Totara 10 (Moodle 3.2.4) and the launcher sends the launched verb correctly to the LRS (using Learning Locker but also tried with SCORM Cloud with the same problem).

Then when the content should send statements I get 401 unauthorised.

Started to test with a Storyline course and then downloaded the prototypes from

https://experienceapi.com/download-prototypes/

Getting the same issue with these.

Trying to find out why this happens but am not sure how the xAPI specification works.

Is it a problem of the content not getting the correct information or of the content not using the information correctly? Where and how are the credentials passed from the launcher to the content?

The tincanlauncher sends it's statement correctly so it's not a settings problem.

**Comment by MartinSandberg** [comment]
Ok... this is what I did to get the tincanpackages to report.

in the function tincanlaunch_get_launch_url (locallib.php)

 // Learning Locker.
        case "0":
            /*
            $creds = tincanlaunch_get_creds_learninglocker($tincanlaunchsettings['tincanlaunchlrslogin'],
                $tincanlaunchsettings['tincanlaunchlrspass'],
                $url,
                $expiry,
                $registrationuuid
            );
            */
           // $basicauth = base64_encode($creds["contents"]["key"].":".$creds["contents"]["secret"]);
            $basicauth = base64_encode($tincanlaunchsettings['tincanlaunchlrslogin'].":".$tincanlaunchsettings['tincanlaunchlrspass']);
            break;

Maybe not the correct way to do it though but for the moment I just need the reporting to work.

**Comment by garemoko** [comment]
@MartinSandberg it looks like what you've effectively done is bypassed the Learning Locker integration. You can achieve the same results by setting the LRS integration to "none". 

My assumption is that there's some kind of bug with the Learning Locker specific integration. Maybe they changed their credential api? I have no plans to look into fixing this, but if somebody makes a PR to fix the issue, I'm happy to review and merge. I suggest talking to your LL vendor if you need the credentials integration to work.  

When you testing with SCORM Cloud - was that with the LRS integration set to "Learning Locker"?

**Comment by MartinSandberg** [comment]
@garemoko just talked to Learning Locker and yes they have changed their API.
Might have a look at the new specifications to see what is needed to change.

Maybe another Learning Locker v2 would be in order to be able to support both their previous API and the new one. What do you think?

**Comment by garemoko** [comment]
That could work, or an extra setting if you select LL to select the version. Or even better if we could automatically detect that somehow.

**Comment by tjr007ma** [comment]
I just installed Learning Locker v2.0 and still not working.

**Comment by MartinSandberg** [comment]
@tjr007ma nothing has been done yet to get it to work with Learning Locker v2.0

**Comment by tjr007ma** [comment]
so what version of the Learning Locker did actually work?

**Comment by garemoko** [comment]
Whatever version was released around the end of 2014 definitely worked with the plugin. This is the learning locker commit that added the functionality: https://github.com/LearningLocker/learninglocker/commit/c72144df842ec4d818f6b294eff17cdeec1c4da8

Note that you can set the integration to "none" to avoid all this LRS specific stuff, it's just you then use the same credentials for every launch.

**Comment by ht2** [comment]
Hey @garemoko, just FYI V2 has a significantly different API structure (it now has full RESTful APIs for all the different models); for reference: http://docs.learninglocker.net/http-models/

**Comment by ht2** [comment]
Specifically, the following would be able to create a client in LLV2 (via cURL at least):

```
curl -X POST \
  https://your.learninglocker.com/api/v2/client \
  -H 'authorization: Basic BASE64CLIENTAUTH' \
  -H 'content-type: application/json'
  -d '{"lrs_id": "LRS_ID", "scopes": ["xapi/all"]}'
```

The client used to create the new client would require the `"ALL"` scope to perform this action. Note how we also must assign the LRS_ID and correct scope via the POST data (otherwise the returned client will not be attached to a store and will be limited in what it can do/retrieve).


And would return you a model with the [following schema](http://docs.learninglocker.net/http-clients/#example-model) (other fields have been added here as per docs):

```
{
	"_id" : "59c2371616bc715f83c34506",
	"createdAt" : "2017-09-20T09:40:44.962Z",
	"updatedAt" : "2017-09-20T09:40:58.376Z",
	"organisation" : "59c2371c16bc715f83c34507",
	"lrs_id" : "59c2371c16bc715f83c34508",
	"title" : "Example Client",
	"scopes" : [
		"xapi/all"
	],
	"isTrusted" : true,
	"authority" : "{\"objectType\":\"Agent\",\"name\":\"New Client\",\"mbox\":\"mailto:hello@learninglocker.net\"}",
	"api" : {
		"basic_secret" : "aaa",
		"basic_key" : "bbb"
	}
}
```

**Comment by garemoko** [comment]
Fixed in master. Will be in next release. (Fixed as in, I renamed the drop down to "Learning Locker 1", not that I made it work with Learning Locker 2)
