### ISSUE TITLE
Retrieving agentProfile set via tincanlaunch

### ISSUE THREAD

**Issue by davidpesce** [davidpesce/moodle-mod_tincanlaunch#146]
I'm getting a 404 when attempting to retrieve the agentProfile (profileId), that was set via the tincanlaunch activity. If I create the same profileId via postman, the xAPI content is able to find the profileId.

I dug through TinCanPHP and saw there was a similar issue over there, but since it's coming from in here, I figured I'd record it and see if you had any insights.

**Comment by garemoko** [comment]
I suspect this is a duplicate of #140, but you just have errors turned off so it fails silently when storing the data.

**Comment by davidpesce** [comment]
Duplicate issue. Closing
