### ISSUE TITLE
Implement Moodle 3.4 support

### ISSUE THREAD

**Issue by michael-milette** [davidpesce/moodle-mod_tincanlaunch#147]
Do you plan on releasing an updated version of this plugin compatible with Moodle 3.4? If so, when?

**Comment by garemoko** [comment]
I currently have no plans to work on this plugin. However if somebody submits a pull request and somebody else reviews it, I will look at merging and releasing it.

**Comment by garemoko** [comment]
Renaming issue as "implement support for 3.4".

@michael-milette can you outline what does not work in 3.4?

**Comment by michael-milette** [comment]
Hi @garemoko , thanks for the quick reply. I haven't actually tried it in Moodle 3.4. I don't personally have access to any xAPI services so I can't test it myself. I am just preparing as I have someone who recently indicated to me that they would like to make use of this plugin with Moodle 3.4 starting next month. For all I know, it might work fine in 3.4 and just needs to be labelled as such with your approval.

**Comment by garemoko** [comment]
Thanks! Let me know once you (or somebody else) test it so we can add that tag.

**Comment by davidpesce** [comment]
This plugin works fine in 3.4 and 3.4.1.
