### ISSUE TITLE
HTTP 401 Unauthorized

### ISSUE THREAD

**Issue by cchiarella2702** [davidpesce/moodle-mod_tincanlaunch#149]
Hi,

My name is Carlos Chiarella and we are using the plugin that is in your GitHub repository. When we tried to create a new Tin Can Launch Activity, we are getting this error:
HTTP 401 Unauthorized","status":401

metadata:
Array
(
    [crypto] => Array
        (
            [protocol] => TLSv1.2
            [cipher_name] => ECDHE-RSA-AES128-GCM-SHA256
            [cipher_bits] => 128
            [cipher_version] => TLSv1/SSLv3
        )

    [timed_out] => 
    [blocked] => 1
    [eof] => 
    [wrapper_data] => Array
        (
            [0] => HTTP/1.1 401 
            [1] => Access-Control-Allow-Headers: Authorization, Content-Type
            [2] => Access-Control-Allow-Methods: OPTIONS, GET, POST, HEAD, PUT, DELETE
            [3] => Access-Control-Allow-Origin: *
            [4] => Access-Control-Expose-Headers: Location
            [5] => Cache-Control: no-cache, no-store, must-revalidate, private
            [6] => Content-Type: application/json
            [7] => Date: Wed, 04 Apr 2018 19:55:45 GMT
            [8] => Server: Watershed
            [9] => Strict-Transport-Security: max-age=31536000
            [10] => Vary: Accept-Encoding,User-Agent
            [11] => WWW-Authenticate: Unauthorized
            [12] => X-Content-Type-Options: nosniff
            [13] => X-Permitted-Cross-Domain-Policies: master-only
            [14] => X-XSS-Protection: 1; mode=block
            [15] => Content-Length: 48
            [16] => Connection: Close
        )

    [wrapper_type] => http
    [stream_type] => tcp_socket/ssl
    [mode] => rb
    [unread_bytes] => 48
    [seekable] => 
    [uri] => https://watershedlrs.com/api/organizations/4394/activity-providers
)

content: {"message":"HTTP 401 Unauthorized","status":401} responseCode: 401

We were able to follow the code until this line:

public function sendRequest($method, $path) in /tincanlaunch/WatershedPHP/watershed.php

Can you please help us with the problem? We are using a Moodle version 3.4.1. 

Thanks for your help,

Carlos Chiarella

**Comment by garemoko** [comment]
Please check that in Watershed the credentials used are configured with API access enabled.

**Comment by cchiarella2702** [comment]
Hi,

Thanks for your answer. I changed the credentials to enable API access.

Now I am getting another error. These are the steps to reproduce the error:

1. Enable the API access in Watershed.
2. Create the activity in Moodle.
3. When I click on the activity, there is a "launch" link.
4. If I click in the "launch" link, I am getting this error:
  
The Learning Record Store is not available. Please contact a system administrator. If you are the system administrator, go to Site admin / Development / Debugging and set Debug messages to DEVELOPER. Set it back to NONE or MINIMAL once the error details have been recorded.
Error attempting to set learner preferences to Agent Profile API.

object(TinCan\LRSResponse)#257 (3) {
  ["success"]=>
  bool(false)
  ["content"]=>
  string(188) "{
  "message" : "Neither If-Match nor If-None-Match headers were set, please check the current state of the resource and set the If-Match header with the current ETag.",
  "status" : 400
}"
  ["httpResponse"]=>
  array(4) {
    ["status"]=>
    int(400)
    ["headers"]=>
    array(4) {
      ["contentType"]=>
      string(16) "application/json"
      ["date"]=>
      string(29) "Fri, 06 Apr 2018 15:05:44 GMT"
      ["apiVersion"]=>
      string(5) "1.0.0"
      ["contentTypeCharset"]=>
      string(10) "ISO-8859-1"
    }
    ["_content"]=>
    string(188) "{
  "message" : "Neither If-Match nor If-None-Match headers were set, please check the current state of the resource and set the If-Match header with the current ETag.",
  "status" : 400
}"
    ["_metadata"]=>
    array(11) {
      ["crypto"]=>
      array(4) {
        ["protocol"]=>
        string(7) "TLSv1.2"
        ["cipher_name"]=>
        string(27) "ECDHE-RSA-AES128-GCM-SHA256"
        ["cipher_bits"]=>
        int(128)
        ["cipher_version"]=>
        string(11) "TLSv1/SSLv3"
      }
      ["timed_out"]=>
      bool(false)
      ["blocked"]=>
      bool(true)
      ["eof"]=>
      bool(false)
      ["wrapper_data"]=>
      array(16) {
        [0]=>
        string(13) "HTTP/1.1 400 "
        [1]=>
        string(155) "Access-Control-Allow-Headers: Content-Type,Content-Length,Authorization,If-Match,If-None-Match,X-Experience-API-Version,X-Experience-API-Consistent-Through"
        [2]=>
        string(54) "Access-Control-Allow-Methods: HEAD,GET,POST,PUT,DELETE"
        [3]=>
        string(30) "Access-Control-Allow-Origin: *"
        [4]=>
        string(169) "Access-Control-Expose-Headers: ETag,Last-Modified,Cache-Control,Content-Type,Content-Length,WWW-Authenticate,X-Experience-API-Version,X-Experience-API-Consistent-Through"
        [5]=>
        string(59) "Cache-Control: no-cache, no-store, must-revalidate, private"
        [6]=>
        string(49) "Content-Type: application/json;charset=ISO-8859-1"
        [7]=>
        string(35) "Date: Fri, 06 Apr 2018 15:05:44 GMT"
        [8]=>
        string(17) "Server: Watershed"
        [9]=>
        string(43) "Strict-Transport-Security: max-age=31536000"
        [10]=>
        string(32) "Vary: Accept-Encoding,User-Agent"
        [11]=>
        string(31) "X-Content-Type-Options: nosniff"
        [12]=>
        string(31) "X-Experience-API-Version: 1.0.0"
        [13]=>
        string(46) "X-Permitted-Cross-Domain-Policies: master-only"
        [14]=>
        string(31) "X-XSS-Protection: 1; mode=block"
        [15]=>
        string(17) "Connection: Close"
      }
      ["wrapper_type"]=>
      string(4) "http"
      ["stream_type"]=>
      string(14) "tcp_socket/ssl"
      ["mode"]=>
      string(2) "rb"
      ["unread_bytes"]=>
      int(188)
      ["seekable"]=>
      bool(false)
      ["uri"]=>
      string(230) "https://watershedlrs.com/api/organizations/4394/lrs/agents/profile?agent=%7B%22objectType%22%3A%22Agent%22%2C%22name%22%3A%22Carlos%22%2C%22mbox%22%3A%22mailto%3Acarlos.chiarella%40rcmusic.ca%22%7D&profileId=CMI5LearnerPreferences"
    }
  }
}
Thanks for your help,

in my institution we are interested in this plugin. Do you have a phone where we can reach you?

Thanks for your help,

Carlos

**Comment by garemoko** [comment]
Please open new issues for new issues. In this case you are seeing a duplicate of https://github.com/garemoko/moodle-mod_tincanlaunch/issues/140
