### ISSUE TITLE
+ in name

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-mod_tincanlaunch#15]
The URL encoding is inserting a plus symbol in the name e.g. Andrew+Downes instead of Andrew Downes.

**Comment by scara** [comment]
You could branch your code based on `if (defined('PHP_QUERY_RFC3986')) {` and keep on using `http_build_query` in the alternate branch passing the result to a string replace like the one above:

```
$rtnString = str_replace('+', '%20', $rtnString);
```

A bit hacky... Or you could try with `lib/weblib.php/moodle_url::get_query_string()` - even if the usage is limited to 'moodle' urls i.e. relative to `$CFG->wwwroot` - by imposing the properties by yourself to map an external URL (never tried by myself).

**Comment by garemoko** [comment]
I did try  `$rtnString = str_replace('+', '%20', $rtnString);` but the trouble is that some of the parameters, particularly the auth credentials (but I guess also the name?) might legitimately include a + sign. 

Instead I've written my own version of the `http_build_query` function. The idea of branching the code was a good one, but I think it's simpler to have the same set of code for everybody.

Here's the fix: https://github.com/garemoko/moodle-mod_tincanlaunch/commit/dcbf91b773bd0a3e3484e42f6ab5c88d7fb569dd
