### ISSUE TITLE
activity_id optional checkbox addition to module settings page on course

### ISSUE THREAD

**Issue by caperneoignis** [davidpesce/moodle-mod_tincanlaunch#150]
This is related to issue #63 articulate story line html5 version does not handle the missing activity_id item like their flash version does. We have sent them a request to fix it, but no telling if they will. I say this to give background for the need to add an option that can be selected by the admin to optionally include the activity_id in the URL. But only on the module settings page within the course. The thinking being, don't turn it on till there is indeed an issue. Since I have seen this issue multiple times in other content forums, I can assume this issue has a risen more then a few times. So to ensure the plugin is flexable enough to handle content that is improperly written, IE can't read it's own tincan.xml file, I will add an additional setting to allow the admin to include the activity_id. 

I was also thinking of adding a text field so the admin can even include what the activity id should look like. Whether it's snake_case or camelCase, which appears to be an issue in some of these cases, is the use of snake_case instead of camelCase. 

I think this may solve a healthy chunk of the issues I have encountered and that I have seen others encounter. 

I may also update the text box for the activityId, or the handler for it, to ensure if a custom id, if different, is used instead of the tincan.xml file, or at least when I attempted the fix listed in #63 I noticed the activity ID text box refused to take the id I put in there and kept defaulting to the course URL.

What are your thoughts @garemoko?

**Comment by garemoko** [comment]
I actually don't see any reason not to always send the activity id if it's provided in the config. Less settings is always good.

**Comment by caperneoignis** [comment]
So, just add this to locallib line 171? 

```
    // Build the URL to be returned.
    // @todo make temporary fix "activity_id" a permanent one with configuration option.
    $rtnstring = $tincanlaunch->tincanlaunchurl."?".http_build_query(
        array(
            "endpoint" => $url,
            "auth" => "Basic ".$basicauth,
            "actor" => tincanlaunch_myjson_encode(
                tincanlaunch_getactor($tincanlaunch->id)->asVersion(
                    $tincanlaunchsettings['tincanlaunchlrsversion']
                )
            ),
            "registration" => $registrationuuid,
            "activity_id" => $tincanlaunch->tincanactivityid
        ),
        '',
        '&',
        PHP_QUERY_RFC3986
    );

    return $rtnstring;
```

**Comment by caperneoignis** [comment]
Or do the activityId string?

**Comment by garemoko** [comment]
Its been a while since I looked at this code but yes, that looks about right. Maybe need to check that $tincanlaunch->tincanactivityid is not empty.

**Comment by caperneoignis** [comment]
Great, I'll work it in.

**Comment by garemoko** [comment]
I'm closing this because I don't plan to work on it and I'm tidying the issues list. PR still very welcome though.
