### ISSUE TITLE
The Learning record store is not available. Please contact system administrator...

### ISSUE THREAD

**Issue by yemjohn** [davidpesce/moodle-mod_tincanlaunch#154]
I have setup Moodle and Learninglocker but I can't find it working when I try to launch my TINCAN.
I get the following error log when I changed the debugger to developer and when I click on the new registration of the first image I got the response on the second image. What could the reason be?
![tincan1](https://user-images.githubusercontent.com/11768346/41287772-793c9588-6e4c-11e8-87cd-0c85ef32b328.JPG)
![tincan2](https://user-images.githubusercontent.com/11768346/41287779-80056fac-6e4c-11e8-9ee5-ee62c55f999b.JPG)

**Comment by garemoko** [comment]
Looks like an LRS or configuration issue. It's returning an HTML document to the state request. 

Have you tried with another LRS? You can get a free watershed account here: http://watershedlrsessentials.com/
