### ISSUE TITLE
ETag issue even though I applied the update (Learning Record Store not available).

### ISSUE THREAD

**Issue by ghost** [davidpesce/moodle-mod_tincanlaunch#155]
I've added this code to three locations in RemoteLRS.php:

else { $requestCfg['headers']['If-None-Match'] = '*'; }

But I'm still getting errors.

Important to note is that Logstore xAPI -DOES- work and it registers the activity on Moodle. So my Watershed LRS works fine and the credentials are proper.

Here's the error message:

The Learning Record Store is not available. Please contact a system administrator. If you are the system administrator, go to Site admin / Development / Debugging and set Debug messages to DEVELOPER. Set it back to NONE or MINIMAL once the error details have been recorded.
Error attempting to set learner preferences to Agent Profile API.

object(TinCan\LRSResponse)#239 (3) {
  ["success"]=>
  bool(false)
  ["content"]=>
  string(188) "{
  "message" : "Neither If-Match nor If-None-Match headers were set, please check the current state of the resource and set the If-Match header with the current ETag.",
  "status" : 400
}"
  ["httpResponse"]=>
  array(4) {
    ["status"]=>
    int(400)
    ["headers"]=>
    array(4) {
      ["contentType"]=>
      string(16) "application/json"
      ["date"]=>
      string(29) "Wed, 01 Aug 2018 14:42:47 GMT"
      ["apiVersion"]=>
      string(5) "1.0.0"
      ["contentTypeCharset"]=>
      string(10) "ISO-8859-1"
    }
    ["_content"]=>
    string(188) "{
  "message" : "Neither If-Match nor If-None-Match headers were set, please check the current state of the resource and set the If-Match header with the current ETag.",
  "status" : 400
}"
    ["_metadata"]=>
    array(11) {
      ["crypto"]=>
      array(4) {
        ["protocol"]=>
        string(7) "TLSv1.2"
        ["cipher_name"]=>
        string(27) "ECDHE-RSA-AES128-GCM-SHA256"
        ["cipher_bits"]=>
        int(128)
        ["cipher_version"]=>
        string(11) "TLSv1/SSLv3"
      }
      ["timed_out"]=>
      bool(false)
      ["blocked"]=>
      bool(true)
      ["eof"]=>
      bool(false)
      ["wrapper_data"]=>
      array(16) {
        [0]=>
        string(13) "HTTP/1.1 400 "
        [1]=>
        string(155) "Access-Control-Allow-Headers: Content-Type,Content-Length,Authorization,If-Match,If-None-Match,X-Experience-API-Version,X-Experience-API-Consistent-Through"
        [2]=>
        string(54) "Access-Control-Allow-Methods: HEAD,GET,POST,PUT,DELETE"
        [3]=>
        string(30) "Access-Control-Allow-Origin: *"
        [4]=>
        string(169) "Access-Control-Expose-Headers: ETag,Last-Modified,Cache-Control,Content-Type,Content-Length,WWW-Authenticate,X-Experience-API-Version,X-Experience-API-Consistent-Through"
        [5]=>
        string(59) "Cache-Control: no-cache, no-store, must-revalidate, private"
        [6]=>
        string(49) "Content-Type: application/json;charset=ISO-8859-1"
        [7]=>
        string(35) "Date: Wed, 01 Aug 2018 14:42:47 GMT"
        [8]=>
        string(17) "Server: Watershed"
        [9]=>
        string(43) "Strict-Transport-Security: max-age=31536000"
        [10]=>
        string(32) "Vary: Accept-Encoding,User-Agent"
        [11]=>
        string(31) "X-Content-Type-Options: nosniff"
        [12]=>
        string(31) "X-Experience-API-Version: 1.0.0"
        [13]=>
        string(46) "X-Permitted-Cross-Domain-Policies: master-only"
        [14]=>
        string(31) "X-XSS-Protection: 1; mode=block"
        [15]=>
        string(17) "Connection: Close"
      }
      ["wrapper_type"]=>
      string(4) "http"
      ["stream_type"]=>
      string(14) "tcp_socket/ssl"
      ["mode"]=>
      string(2) "rb"
      ["unread_bytes"]=>
      int(188)
      ["seekable"]=>
      bool(false)
      ["uri"]=>
      string(246) "https://watershedlrs.com/api/organizations/3694/lrs/agents/profile?agent=%7B%22objectType%22%3A%22Agent%22%2C%22name%22%3A%22Aaron%20van%20der%20Brugge%22%2C%22mbox%22%3A%22mailto%3Aaaronvdbrugge%40gmail.com%22%7D&profileId=CMI5LearnerPreferences"
    }
  }
}

**Comment by garemoko** [comment]
Hi Aaron, 
Looking at our logs from August 4th, it looks like you resolved this issue yourself and the documents are being stored in Watershed.

Is that correct?

**Comment by ghost** [comment]
Correct! You're good to figure that out so quickly! :)

I had to apply several fixes manually. Not just the eTag one. 

By the way, is it possible to manually create a registration ID so that we can call the launch link directly without having to click on New Registration? 

We are developing an app that will function as a portal for e learning modules and one of the functions would be to open a Tin Can Captivate module directly without having to display Moodle. Anyway there's more to that but basically we need to figure out a way to create a working registration ID for the launch link. 

Thank you :)

**Comment by garemoko** [comment]
@twinmatrix I'd be very interested to have a list of fixes you had to make. 

It is possible to launch without Moodle. This javascript prototype might help: https://github.com/WatershedLRS/xAPI-launch

You might want to consider  generating new credentials for each launch too (for security reasons). See https://watershedlrs.zendesk.com/hc/en-us/articles/115001767686-Credentials-API

**Comment by ghost** [comment]
@garemoko 

Thank you for your reply. I applied #90 and #83.

How should I use the individual xAPI launch? Can I just upload that package to my own server and add Contents and a proper tincan.xml and then run launch.html?
Because I see it reference TinCan I'm assuming a lot more needs to be added, and perhaps my thought about it is wrong.

Also, if we do that and host the Tin Can modules outside of Moodle, we would also like to use those for the modules on Moodle. So that we don't have to upload them to Moodle AND to our individual server. But is it possible to link to the Tin Can module from Moodle after adding launch.html and the other separate code?

Thanks again. :)

**Comment by garemoko** [comment]
yes, the launch.html can basically be an alternative way to launch the content instead of Moodle. There's no extra files need adding.

**Comment by twinmatrix** [comment]
How would it, for example, get the class TinCan if it's hosted individually on my website?

For example this piece of code:

> function sendStatement (){
    var lrs;

    try {
        lrs = new TinCan.LRS(
            {
                endpoint: config.endpoint,
                username: config.key,
                password: config.secret,
                allowFail: false
            }
        );
    }

Doesn't it need TinCanPHP somewhere so it can know what "TinCan.LRS" is? Sorry if I'm explaining this very poorly...
I would only upload these 5 files + Content, so I'm not sure where it would get all necessary TinCan API etc. information from.

**Comment by ghost** [comment]
Awesome, thank you! It works great.

Is there a way to start a Tin Can module right away when you click on it, instead of having to click on "New Registration"? That seems like a redundant step from the Point of View of users.

**Comment by ghost** [comment]
Oh, one more question. I need the module to open in the current window instead of a new one, so I tried this:

> window.open(launchLink),"_self");

But it gives me an error that there is a problem communicating with the LRS and that it might be my internet connection.

What should I do?

Thank you.

**Comment by ghost** [comment]
I hope I didn't ask too much. :)
I cleaned up my posts to make them shorter. @garemoko

**Comment by garemoko** [comment]
> Is there a way to start a Tin Can module right away when you click on it, instead of having to click on "New Registration"? 

I there is a config option for this. See https://github.com/garemoko/moodle-mod_tincanlaunch/blob/master/mod_form.php#L228

> I need the module to open in the current window instead of a new one

This will break a few things like completion tracking so is not something you will be able to do a quick change for. You'll need to work through view.php very carefully and come up with some solution to completion tracking that does not require a Moodle window to be left running.

**Comment by ryasmi** [comment]
I think you tagged me accidentally here @twinmatrix 👍

**Comment by ghost** [comment]
@garemoko 
Should I comment line 228 out or set this to 0:

https://github.com/garemoko/moodle-mod_tincanlaunch/blob/master/mod_form.php#L230

Sorry Ryan!

**Comment by garemoko** [comment]
@twinmatrix Can you just configure that setting in your modules? Best not to edit the code if you can avoid it.

**Comment by ghost** [comment]
@garemoko 
I did create a new module with Multiple Registrations turned off, but then when I want to play the module I am taken to this page:

![screen shot 2018-08-10 at 14 43 42](https://user-images.githubusercontent.com/15997983/43958477-dd702960-9cab-11e8-9bd5-16f2d9aa6b28.png)

**Comment by garemoko** [comment]
Interesting. That looks like a bug. Please open a separate ticket for that. 

Note that I'm not currently actively maintaining this repo so if you need this fixed, you should look to contract a developer to address it. I will merge any fixes that have been appropriately reviewed.

**Comment by ghost** [comment]
@garemoko 
Sure! Alright, I'll do that. Thanks for all your replies.
Just one more thing, if I downgrade to PHP 5.6 should it fix the issues? I mean, did you develop this repo with PHP 5.6 in mind? I'm currently in the process of downgrading and I'll have to reinstall Moodle but it will be worth it if the plugin works properly.

Also, do you know any community where I could find a developer who is educated in this subject?

Thanks again.

**Comment by garemoko** [comment]
I don't have any reason to believe that this particular issue is related to the Moodle version, but also I guess there's no reason to believe it's not either.

The best place to look for Moodle developers is the Moodle partners directory: https://moodle.com/partners/?country=united-kingdom

Leo Learning in particular have prior experience with this plugin: https://leolearning.com/

If it was part of a paid Watershed implementation project, it might also be something we might take on. I can link you up to the Watershed sales team if you'd like to discuss that.

**Comment by ghost** [comment]
Thanks a lot! 👍

**Comment by garemoko** [comment]
This issue is a series of questions and there's no clear action to take, so I'm closing this to tidy up the issues list.
