### ISSUE TITLE
Plugin keeps creating new Watershed Activity Providers?

### ISSUE THREAD

**Issue by ghost** [davidpesce/moodle-mod_tincanlaunch#156]
![screen shot 2018-08-07 at 19 11 34](https://user-images.githubusercontent.com/15997983/43791845-422100e6-9a77-11e8-9b10-a8a79a69b27a.png)

This seems like an issue, why is it happening? There will be 100s, 1000s of Activity Providers?

I don't think they're even used because I just enter the original Activity Provider that I created myself.

**Comment by garemoko** [comment]
Yes, this is a known issue, though if you have cron running it should tidy them, up. 

See https://github.com/garemoko/moodle-mod_tincanlaunch/issues/142. It needs some work.

**Comment by ghost** [comment]
Great, thank you.

How can I get cron to tidy them up?

**Comment by garemoko** [comment]
If you have cron running, it should happen automatically. See
https://docs.moodle.org/35/en/Cron#Setting_up_cron_on_your_system

For testing also see: https://docs.moodle.org/35/en/Cron#The_web_based_Moodle_cron_command
