### ISSUE TITLE
Watershed Activity Providers are not cleaned up by expire credentials

### ISSUE THREAD

**Issue by ghost** [davidpesce/moodle-mod_tincanlaunch#157]
I'd like to try debugging a bit myself, but I'm not sure how to go about that.

For example I'd like to add a few echos to expire_credentials.php to see what is going wrong, if the function is even actually being played. But I'm not sure how to then run the php file so that my browser console catches the echos.

The "Run Now" button on Moodle for the plugin seems to run the php within its framework so I don't actually see what is going on... And I can't run the php from my console for some reason... Any advise much appreciated.

**Comment by garemoko** [comment]
See the web based cron command here: https://docs.moodle.org/35/en/Cron#The_web_based_Moodle_cron_command

This is what I used for debugging when creating this script in the first place. 

If you have time to work on this, you might consider updating the script to use Watershed's credential sessions API at the same time. That's something that I'd love to do if/when I can allocate time to work on this plugin. https://watershedlrs.zendesk.com/hc/en-us/articles/115001767686-Credentials-API

**Comment by garemoko** [comment]
Will be fixed by #142 so closing this as a duplicate since I have no plans to fix this before #142.
