### ISSUE TITLE
upgrade.php in wrong order

### ISSUE THREAD

**Issue by davosmith** [davidpesce/moodle-mod_tincanlaunch#158]
The upgrade steps in upgrade.php are in a fairly random order, which results in a fatal error when upgrading several versions at once.

e.g. if oldversion is 2016010100 (just an example, I haven't checked exact version numbers), then the upgrade step for 2016021508 will run, calling upgrade_mod_savepoint and setting the version to 2016021508.
After that it will try to run the 2016021502 upgrade step (as oldversion is unaltered), calling upgrade_mod_savepoint and setting the version to 2016021502, which is earlier than the version just set, causing an error.

Solution: reorder upgrade.php to make sure all upgrade steps are in ascending order.

**Comment by garemoko** [comment]
Fixed in master. Will be in next release.
