### ISSUE TITLE
XAPI support in Moodle Mobile

### ISSUE THREAD

**Issue by f2dwire** [davidpesce/moodle-mod_tincanlaunch#159]
Hello

First of all, thanks for making this awesome great plugin available. 

Are there any plans to make the plugin available in Moodle Mobile?  It would be a wonderful experience to get  xAPI working in Moodle Mobile
Thanks

**Comment by garemoko** [comment]
I currently have no plans to extend this to Moodle Mobile, but if you want to extend it I am happy to answer any questions you may have.
