### ISSUE TITLE
Is it possible to access mod information through Web API?

### ISSUE THREAD

**Issue by aaronvdbrugge** [davidpesce/moodle-mod_tincanlaunch#165]
HI guys,
Is it possible to access the mod's information through Moodle's web API?

core_course_get_contents might be useful but I can't figure out how to actually get the mod info. I can only manage to get the name and 'URL' (but actually it's the URL to the page on Moodle, not the Tin Can launch URL).

It'd be great, for example, to retrieve Activity ID and tags.

Here's the API: https://www.refineddata.com/api/

Thanks,

**Comment by garemoko** [comment]
I'm not familiar with that API. This would need to be a question to ask the company that provides that API I think.
