### ISSUE TITLE
Additional launch options

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-mod_tincanlaunch#166]
Currently it's possible to either show a list of previous saved attempts to return to, or it's possible to always launch the same attempt. It would be good to add the option to always launch a new attempt. 

In addition for always new attempt or always same attempt modes, there's no reason to force the user to click a launch button - it should just open automatically.

**Comment by davidpesce** [comment]
Implemented in 035b40e7c135393deaff6b8d8a8f12505a5620b1
