### ISSUE TITLE
Failed marker?

### ISSUE THREAD

**Issue by danielgavriliuc** [davidpesce/moodle-mod_tincanlaunch#167]
How can i have the failed marker? i can't get out of this, the completion work ok and i recive the "completed" marker, but if i fail the quiz or i don't see enough slides to complete the activity (tested with captivate and articulate) the marker remains "not completed".

**Comment by garemoko** [comment]
Hi, 
The completion functionality for this plugin does not currently support pass and failed completion states. These would need to be added. 

I'm of the opinion that the completion tracking functionality of this plugin needs to be completely re-written anyway, so if you are looking to add pass/fail tracking, I'd encourage you to look at re-working completion tracking at the same time. 

Andrew

**Comment by davidpesce** [comment]
Completion has been partially rewritten, but there is a more generic issue that relates to grades here: #227
