### ISSUE TITLE
un-fork TinCanPHP

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-mod_tincanlaunch#168]
Now https://github.com/RusticiSoftware/TinCanPHP/pull/90 has been merged, the TinCanPHP submodule should point back at https://github.com/RusticiSoftware/TinCanPHP instead of https://github.com/garemoko/TinCanPHP/tree/a789935e48d14b8c6828b3692a560894c4dedd85

**Comment by davidpesce** [comment]
Fixed via #185
