### ISSUE TITLE
The Tin Can launch link

### ISSUE THREAD

**Issue by youmnah** [davidpesce/moodle-mod_tincanlaunch#17]
Hi, I'm using Tin can launch link I put : 
the TCAPI Query from SCORM CLoud LRS viewer in Endpoint 
Basic login and Basic Password are the Key and Secret from Activity Providers
launch URL and Activity Key: http://tincanapi.co.uk ( I put it like this because I have no idea what should I put so please if it's wrong tell me what should I put).
There's no error and that's what I have:  
![image](https://cloud.githubusercontent.com/assets/6929457/3051515/eda3e174-e18d-11e3-81e0-ce0cfe7d1371.png)
When I lanch this activity I have this:
![image](https://cloud.githubusercontent.com/assets/6929457/3051652/f4850df4-e18f-11e3-828b-d98e4f62080b.png)
Why it's like this and it's not displayed properly. Any Advise is highly apreciated. Thanks in advance:)

**Comment by garemoko** [comment]
Try these settings:

Launch URL: http://localhost/xapi/GolfExample_TCAPI/index.html

Activity id: http://localhost/xapi/GolfExample_TCAPI/index.html

Endpoint: http://cloud.scorm.com/ScormEngineInterface/TCAPI/public/

Basic Login: X

Basic Password: X

Version: 1.0.0

**Comment by youmnah** [comment]
It's giving me an error 404 :The requested URL was not found on this server. The link on the referring page seems to be wrong or outdated. Please inform the author of that page about the error.

**Comment by garemoko** [comment]
Are you still able to launch the activity?

**Comment by garemoko** [comment]
Screenshot please

**Comment by youmnah** [comment]
![image](https://cloud.githubusercontent.com/assets/6929457/3069591/f9d30c0c-e29d-11e3-84c4-a9bb69f04942.png)
![image](https://cloud.githubusercontent.com/assets/6929457/3069603/2b1e9a10-e29e-11e3-8d58-d7e979e0f1de.png)

**Comment by youmnah** [comment]
But I wanted to ask you this plugin is used to launch tin can courses and not LRS not? but before if you noticed I could access the statements but it wasn't well displayed so can I still have all the LRS statements in my moodle?? thank you for your help and quick replies:D

**Comment by garemoko** [comment]
Sorry, I gave you the wrong settings. Replace launch url and activity id with the address to your content. 

You could write a plugin to display statements in Moodle. Take a look at the Tin Can learner stream plugin.
