### ISSUE TITLE
Unable to add activity

### ISSUE THREAD

**Issue by rschrenk** [davidpesce/moodle-mod_tincanlaunch#172]
Hi, when I want to add an activity it breaks showing the following error
<img width="702" alt="tincan-error" src="https://user-images.githubusercontent.com/8080807/65187527-69ed6700-da6c-11e9-8713-b01420fd9020.png">

**Comment by rschrenk** [comment]
Hello,

I figured out that it has to do with "$this->standard_coursemodule_elements();" in mod_form.php. If I disable all feature-support in lib.php then it shows the same error but instead of MoodleQuickForm_checkbox moodleQuickForm_select.

Unfortunately I have no idea for now what may cause this error.

Is there anybody still concerned with this plugin or is it at a dead end?

Kind regards

**Comment by rschrenk** [comment]
If anybody wants to solve that issue, there is the next clue:

In mod_form go to add_completion_rules and comment all occurences of "$mform->addGroupRule". The form will show!

**Comment by garemoko** [comment]
> Is there anybody still concerned with this plugin or is it at a dead end?

I'm no longer working on this plugin and it's available if a new maintainer wants to pick it up.

**Comment by davidpesce** [comment]
@rschrenk are you still having issues with this?

**Comment by rschrenk** [comment]
Hi, after the reply of @garemoko i gave up. After your reply, I gave it a second chance and installed the latest plugin in our Moodle test sytem (already 3.9).

Same error.

![tincanlaunch](https://user-images.githubusercontent.com/8080807/84866364-e5bb2500-b079-11ea-95a9-60244878dd41.png)

**Comment by davidpesce** [comment]
This looks like a larger issue with your Moodle instance. Is this an upgraded Moodle or fresh install?

If it’s an upgrade, I’m guessing there are some corrupt or missing Core files: https://tracker.moodle.org/plugins/servlet/mobile#issue/MDL-16804

Also, can you tell me what version of PHP you’re using? Any other info about your server environment may help.

**Comment by rschrenk** [comment]
The first issue appeared on another test machine that used Moodle 3.5.
This time it is a fresh install of Moodle 3.9. We use apache2 and php 7.2.30

**Comment by davidpesce** [comment]
Hmm, I can't replicate it on a new install of 3.9 and have it running on multiple 3.5-3.8 instances. 

I'm beginning to wonder if it's an issue with either the language (looks like you have German and I'm testing in English). Any chance you can switch to English and try again?

Also, is this when you click to add the activity or after you've added the activity values and you're submitting them?

The other thing I'm curious about is the theme. Are you using the default boost theme or something else?

**Comment by rschrenk** [comment]
This is weird - I also get the very same error after setting the language to English.
![error](https://user-images.githubusercontent.com/8080807/85408848-5b852c00-b565-11ea-8bad-b88143e0c15a.png)

**Comment by davidpesce** [comment]
What about the theme? Can you set it to Boost and try again?

Sorry about all the requests, I'm struggling to figure out what is causing this.

**Comment by rschrenk** [comment]
Hi, I investigated the code and found, that for some reason a block has no name!
I added in classes/form/addblock.php before lin 131 the following code:
`echo "ADD SIBLING " . print_r($sibling, 1) . "\n";`
and got as result:
`ADD SIBLING stdClass Object ( [id] => 37 [blockname] => [parentcontextid] => 1 [showinsubcontexts] => 1 [requiredbytheme] => 1 [pagetypepattern] => * [subpagepattern] => [defaultregion] => side-pre [defaultweight] => 0 [configdata] => [timecreated] => 1587497593 [timemodified] => 1587497593 ) `

In database, this block is
`37 | site_main_menu | 0 | 0 | 1`

Kind regards

**Comment by rschrenk** [comment]
I changed line 118 to
`if ($sibling->blockname == 'multiblock' || empty($sibling->blockname)) {`

**Comment by rschrenk** [comment]
puh, this did not work either. With var_dump I found out, that $sibling->blockname is a space character!
So a quick fix was in line 118
`if ($sibling->blockname == 'multiblock' || empty(str_replace(' ', '', $sibling->blockname))) {`

**Comment by rschrenk** [comment]
> What about the theme? Can you set it to Boost and try again?
> 
> Sorry about all the requests, I'm struggling to figure out what is causing this.

I tried boost and classic - same error.

**Comment by davidpesce** [comment]
Hmmm, classes/form/addblock.php is Moodle core code. I wouldn't recommend changing that.

Did the below fix the issue for you?

> So a quick fix was in line 118
> `if ($sibling->blockname == 'multiblock' || empty(str_replace(' ', '', $sibling->blockname))) {`

**Comment by rschrenk** [comment]
Yes, but I am not sure if I would suggest this as a solution. I think it is more a quick-fix. It works, but I do not see all blocks.

**Comment by davidpesce** [comment]
What's strange is that the tincanlaunch plugin isn't a block. Do you have other blocks installed that may be the ultimate cause of the issue?

**Comment by rschrenk** [comment]
Oh, I am so sorry, I mixed two issues. I posted this in the wrong one.

**Comment by rschrenk** [comment]
I removed my comments here, that were wrong.

**Comment by davidpesce** [comment]
> Oh, I am so sorry, I mixed two issues. I posted this in the wrong one.

Ahh, no worries. Let's start at the top.

- Can you try it with boost/clean theme?
- Can you try when switching it to the English language?
- Does your Moodle 3.9 install have any other plugins installed?
- Does the error appear when you click to add the activity or after you've added the activity values and you're submitting them?

**Comment by davidpesce** [comment]
Guessing this is all fixed. Closing for now, but let me know if this is still an issue.

**Comment by rschrenk** [comment]
No, the error is still there. sorry. But I had no time for now to test your suggestions.
