### ISSUE TITLE
Warning: Invalid get_string() identifier: 'tincanlaunch:view' or component 'mod_tincanlaunch'.

### ISSUE THREAD

**Issue by kristian-94** [davidpesce/moodle-mod_tincanlaunch#173]
Looks like we're missing some lang strings for capabilities. 
1. Install this plugin master branch.
2. Turn up developer debug settings
3. Visit https://yoursite.com/admin/tool/capability/index.php
4. You will get the warning: 

> Invalid get_string() identifier: 'tincanlaunch:view' or component 'mod_tincanlaunch'. Perhaps you are missing $string['tincanlaunch:view'] = ''; in mod/tincanlaunch/lang/en/tincanlaunch.php?
> 
>     line 353 of /lib/classes/string_manager_standard.php: call to debugging()
>     line 7260 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
>     line 2529 of /lib/accesslib.php: call to get_string()
>     line 44 of /admin/tool/capability/index.php: call to get_capability_string()

Should be a simple fix to add these strings to our lang file.

**Comment by davidpesce** [comment]
Merged. Thanks for the commit!
