### ISSUE TITLE
content_token & content_endpoint

### ISSUE THREAD

**Issue by alt95** [davidpesce/moodle-mod_tincanlaunch#177]
According to  https://github.com/RusticiSoftware/launch/blob/master/lms_lrs.md  which the launcher follows there should be a way to access the content_token & content_endpoint somehow. Is there something particular we have to enable in order to get a handle on these from the launch url?

**Comment by davidpesce** [comment]
Hi @alt95 - This is an aspect of the Rustici launch spec that I'm not familiar with. Looking at it, it only pertains to content that is protected (let's say hosted on an LMS). The LMS would also have to support this.

The current implementation of this plugin does not take into account the content_token nor the content_endpoint. It also doesn't take into account hosting the content on the LMS. From our perspective, cmi5 is the future of launching xAPI content from the LMS. 

That all said, I do like the idea of this. If you want to contribute it as a PR, we can evaluate and add it.
