### ISSUE TITLE
Tin Can Plugin not communicating with LRS's

### ISSUE THREAD

**Issue by paulraper** [davidpesce/moodle-mod_tincanlaunch#18]
I've been trying to get some Articulate modules to work with the tincan plugin, but it doesn't seem to matter which LRS I use, I simply don't seem to get any data back.
When I check the LRS, there is some data there, but the data doesn't seem to get pulled/sent back to Moodle, so the Impression is that the user hasn't done anything.

**Comment by garemoko** [comment]
Hi Paul, 

Please can you provide screenshots of your settings and a link to your content? 

If you're using Storyline can you check you've published it for Tin Can tracking, You're using Storyline 2 and you've modified the package following this example here: https://github.com/garemoko/StoryCanJS/compare/d3516551b4983a9e7348aaaef6f1c38dee874b8a...master 

Andrew
