### ISSUE TITLE
Plugin settings have no help

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-mod_tincanlaunch#19]
There's no help text for the global plugin settings.

**Comment by davidpesce** [comment]
If I make a change to lang/en/tincanlaunch.php (adding a new help string), does this require a upgrade? 

If I change an existing help string and purge all caches, the change appears. Adding a new string doesn't seem to populate.

**Comment by garemoko** [comment]
It might well do, strings are stored in the database. Might be a question for the Moodle forums if its not easy to work out, but hopefully you can just increment the version number.

**Comment by davidpesce** [comment]
I'm a dolt, just forgot to add it to settings.php properly. It doesn't require an update. I'll have this over shortly.

**Comment by davidpesce** [comment]
OK, here's what I've got. 
![Imgur](http://i.imgur.com/ngdJrlc.png)

Thoughts?

**Comment by garemoko** [comment]
Looks good. You can probably delete "(min)" from Duration now that you have the description. 

How about something like "Use Insecure basic authentication unless another settings is explicitly supported by your LRS"? I don't think we should name specific LRSs.

**Comment by davidpesce** [comment]
Got it! Do you want me to move the Auth options to the language file? Or leave them where they are?

**Comment by garemoko** [comment]
Yes, any English strings that display to the user should go in the language file please!

**Comment by garemoko** [comment]
Confirmed fixed by #44
