### ISSUE TITLE
Launch link should be constructed using functions for serializing JSON and assembling URLs

### ISSUE THREAD

**Issue by fugu13** [davidpesce/moodle-mod_tincanlaunch#2]
This will ensure it is always valid, unlike string concatenation

**Comment by garemoko** [comment]
Thanks Russell, that makes sense.

**Comment by garemoko** [comment]
This is addressed on the development branch here: https://github.com/garemoko/moodle-mod_tincanlaunch/commit/6ec949693e91e8fe135cd366f3b761868363b456

Closing the issue. Please re-open if you think this needs to be looked at again.
