### ISSUE TITLE
Package is opened outside the Moodle

### ISSUE THREAD

**Issue by abhinandankhatawane** [davidpesce/moodle-mod_tincanlaunch#202]
Hi,

I tried this and works perfectly fine. However upon launching the Course, the course is opened outside the Moodle in a new tab. I am expecting the course to open withing the Moodle framework. 

Is that possible? If yes, how to achieve that?

Thanking you in advance.

**Comment by davidpesce** [comment]
There currently is not a way to do this because xAPI doesn't return a closing URL (a URL to return to after completing the course). cmi5 has addressed this and we have plans to incorporate it into this plugin (or a separate one).
