### ISSUE TITLE
Request failed: ErrorException: fopen(): SSL operation failed with code 1. 

### ISSUE THREAD

**Issue by abhujbal** [davidpesce/moodle-mod_tincanlaunch#203]
Hi, 
I have LRS (Learning Locker) with the HTTPS URL.
I am trying to add LRS endpoint with **HTTPS** URL in Tincan Setup Tin Can Launch Link setting in moodle and after that, I got below error. The endpoint is with Learning Locker.  

Error attempting to get registration data from State API.

object(TinCan\LRSResponse)#1308 (3) {
  ["success"]=>
  bool(false)
  ["content"]=>
  string(960) "Request failed: ErrorException: fopen(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in /var/www/html/pwclms/mod/tincanlaunch/TinCanPHP/src/RemoteLRS.php:150
Stack trace:
#0 [internal function]: TinCan\RemoteLRS->TinCan\{closure}(2, 'fopen(): SSL op...', '/var/www/html/p...', 150, Array)
#1 /var/www/html/pwclms/mod/tincanlaunch/TinCanPHP/src/RemoteLRS.php(150): fopen('https://pwclrs....', 'rb', false, Resource id #204)
#2 /var/www/html/pwclms/mod/tincanlaunch/TinCanPHP/src/RemoteLRS.php(669): TinCan\RemoteLRS->sendRequest('GET', 'activities/stat...', Array)
#3 /var/www/html/pwclms/mod/tincanlaunch/locallib.php(381): TinCan\RemoteLRS->retrieveState(Object(TinCan\Activity), Object(TinCan\Agent), 'http://tincanap...')
#4 /var/www/html/pwclms/mod/tincanlaunch/view.php(106): tincanlaunch_get_global_parameters_and_get_state('http://tincanap...')
#5 {main}"
  ["httpResponse"]=>
  NULL
}

Is there anything else we need to set up for using the **HTTPS** URL.

So please update us on this error.
Thanks in Advance.

**Comment by davidpesce** [comment]
Hi @abhujbal - thanks for submitting the issue over here!

It looks like your certificate on your LRS is invalid. Is it a self-signed certificate? If so, I'd recommend using something like LetsEncrypt (via certbot) to get a valid certificate.

**Comment by abhujbal** [comment]
Hi David,

We have bought it from Godaddy.

**Comment by abhujbal** [comment]
Hi David,

We have bought SSL from Godaddy.

One more thing I want to confirm with you that the SSL certificate on site is working well and all the setting is at the proper place.  So do we need to install an SSL certificate for TLS also?

Please update.

**Comment by abhujbal** [comment]
Hi David,

Can you please let me know that can we use the **HTTPS** with the endpoint URL into the plugin.
Because where ever we checked with the docs, video tutorial for the plugin all they have used the endpoint URL with **HTTP**.

Please update.

Thanks in advance.

**Comment by davidpesce** [comment]
Hi @abhujbal - unfortunately, there isn't anything we can do on our end. From what I understand of the error, the cert on your LRS is invalid and when you switch to using SSL (HTTPS), the plugin fails. I can assure you that we have it running on 30+ instances with HTTPS without an issue.
