### ISSUE TITLE
Build Manifest

### ISSUE THREAD

**Issue by Getafix-hub** [davidpesce/moodle-mod_tincanlaunch#205]
I noticed some difference between the files in the official version 1.5 (Build: 2018110100) (2018110100) and the master branch. 
Is there a manifest describing what files should be put in the ZIP file to be installed via the Moodle UI?

**Comment by davidpesce** [comment]
Hi @chrgrd - the github repo is the latest and greatest code to be used. The moodle plugin repository is outdated due to an issue with automated deployment of plugin code to the plugin repository.
