### ISSUE TITLE
Simplified single registration launch user interface

### ISSUE THREAD

**Issue by Getafix-hub** [davidpesce/moodle-mod_tincanlaunch#206]
This issue is to track a proposed enhancement to simplify the launch user interface  for single registration. 
It can be viewed as a stepping towards this roadmap feature:  
Option to always launch a new attempt (#166) and launch the content directly
When multiple registrations and disabled, a new option should allow to select the simplified launch interface by abstracting  the concept of initial launch with registration versus further simple launch in a unified "click to launch" user experience

**Comment by davidpesce** [comment]
Thanks for your contribution! I was able to use some of it and it has been implemented here: 035b40e7c135393deaff6b8d8a8f12505a5620b1
