### ISSUE TITLE
track completion by verb does not check that the object is the specified activity id 

### ISSUE THREAD

**Issue by Getafix-hub** [davidpesce/moodle-mod_tincanlaunch#209]
The help with Track completion by verb specifies: 
_Moodle will look for statements where the actor is the current user, **the object is the specified activity id** and the verb is the one set here. If it finds a matching statement, the activity will be marked complete._

The use case is an xAPI activity which:
- contains quizzes
- uses track completion by verb using http://adlnet.gov/expapi/verbs/passed or http://adlnet.gov/expapi/verbs/failed 
- generating a score and a passed / failed verb based on the number of viewed slides

In this case, multiple passed / failed statements can be generated within a single activity and the object id must be properly tested to match the desired condition. 

Example: 

Tincanlaunch configuration
Completion tracking: Show activity as complete when conditions are met
Activity ID: **http://localhost/localcontent/HelloB**
Track completion by verb: http://adlnet.gov/expapi/verbs/passed

Quiz passed statement: 
verb id: http://adlnet.gov/expapi/verbs/passed
objectType: Activity
object id: **http://localhost/localcontent/HelloB/quizzes/bqu2bgm3t729-kgs9lqf9hvku**

Activity passed based on number of viewed slides score
verb id: http://adlnet.gov/expapi/verbs/passed
objectType: Activity
object id: **http://localhost/localcontent/HelloB**

**Comment by davidpesce** [comment]
Resolved via 12ded5d58b4e306e11ffb0e1f9fbe83c7102cbb8
