### ISSUE TITLE
Changing the label text on the launch links

### ISSUE THREAD

**Issue by scorponoc333** [davidpesce/moodle-mod_tincanlaunch#211]
How do I change the string that says "launch" to something else like "Resume course"?

I have the same question regarding the Start New Registration button but I assume I will get that answer if I can answer the first question.

**Comment by Getafix-hub** [comment]
Currently, these strings are hardcoded and would require a custom build of the plugin
Take a look at tincanlaunch.php file for the desired language (e.g tincanlaunch\lang\en for english). 
$string['tincanlaunchviewlaunchlink'] = 'launch';

**Comment by scorponoc333** [comment]
> Currently, these strings are hardcoded and would require a custom build of the plugin
> Take a look at tincanlaunch.php file for the desired language (e.g tincanlaunch\lang\en for english).
> $string['tincanlaunchviewlaunchlink'] = 'launch';

Thank you very much!

**Comment by davidpesce** [comment]
@scorponoc333 - you could also modify the language string (via Moodle admin) to something you'd rather see.
