### ISSUE TITLE
New Version on Moodle Plugins Directory

### ISSUE THREAD

**Issue by justin-castleman** [davidpesce/moodle-mod_tincanlaunch#212]
When do you anticipate that there will be a new version of the plugin published to the Moodle Plugins Directory? We are running the most recent version that is available from there and would like to incorporate the fixes that you have made thus far as it appears that this will fix several of our issues we are having with Moodle and LearningLocker now.

**Comment by davidpesce** [comment]
Hi @justin-castleman - Unfortunately, I won't be updating the Moodle plugin directory until Moodle allows auto-publishing from source control platforms (like github). They're working on it, so I'm hopeful it'll be available at some point this year.

That said, the code available here is stable and I'm running it in production. You can download the latest from here and upload it to your production instance.

**Comment by justin-castleman** [comment]
@davidpesce, thanks for the reply. We were able to update the plugin directly from the source code and it appears that this fixed our issues we are seeing.
