### ISSUE TITLE
The Learning Record Store is not available.

### ISSUE THREAD

**Issue by nileshnpathade** [davidpesce/moodle-mod_tincanlaunch#214]
![image](https://user-images.githubusercontent.com/13468332/111617255-e0f1f000-8808-11eb-8feb-3600611825dc.png)

I am unable to understand what is issue it is.

I have using Moodle 3.8 

![image](https://user-images.githubusercontent.com/13468332/111617394-0da60780-8809-11eb-811b-769a1a047196.png)

"http://tincanapi.co.uk/stateapikeys/registrations"

URL also not working.

Please assist me

**Comment by davidpesce** [comment]
Hi @nileshnpathade - that is the URI that is used for determining the state and is not a browse-able resource. You'll need to input your own LRS URL and credentials via the mod_tincanlaunch plugin settings.
