### ISSUE TITLE
The Learning Record Store is not available for lxHive LRS

### ISSUE THREAD

**Issue by maximum2000** [davidpesce/moodle-mod_tincanlaunch#215]
Plugin works fine for cloud.scorm.com/lrs/ and watershedlrs.com but doesn't work with LRS lxHive (https://github.com/g3i/lxHive)
Error - The Learning Record Store is not available
My test LRS is 
var endpoint = "https://lrs.lcontent.ru/";
var auth =  "Basic " + toBase64('2eUGHaH3dEu7vkURXyQjEpKmidb46IM2qLPM5sRM:To3QouwxBNwjt6xQosvP18mm6qeslf7WDXNSEagd');

**Comment by davidpesce** [comment]
Hi @maximum2000 - we'll need further details in order to troubleshoot. It's most likely a difference in how the lxHive LRS implements the authentication. You may be able to adjust the mod_tincanlaunch plugin settings to accommodate the differences.
