### ISSUE TITLE
Add full support for cmi5

### ISSUE THREAD

**Issue by brendanheywood** [davidpesce/moodle-mod_tincanlaunch#216]
This is mentioned in the readme:

https://aicc.github.io/CMI-5_Spec_Current/

**Comment by davidpesce** [comment]
A separate cmi5 plugin is being created for Moodle.

**Comment by LiamKearn** [comment]
Hi @davidpesce or @brendanheywood,

Did either of you find an open source solution for this?

**Comment by LiamKearn** [comment]
Apologies for the ping. It was much easier to find one today (https://github.com/adlnet/cmi5-player-moodle-plugin), I'd searched briefly a few days ago and found nothing!

If you found any alternatives that don't require catapult that would be great!

**Comment by servosdesign** [comment]
@LiamKearn did you manage to get that plugin working? I can't get it to work inside moodle

**Comment by LiamKearn** [comment]
> @LiamKearn did you manage to get that plugin working? I can't get it to work inside moodle

I did install it and gave it a go on a local newer version of MOODLE (IIRC ~4.1), it seemed to have some upgrade work that needed doing to support newer versions of MOODLE.

It also requires the catapult player system to actually function which I was using locally for conformance testing but seems a bit wasteful at production scale.

My advice would be to look into the SCORM cloud functionality (and it's [plugin](https://github.com/RusticiSoftware/SCORMCloud_MoodleModule) with MOODLE) if you just need to get CMI5 content working with MOODLE. I'm not sure that plugin is maintained and updated also but it's by the catalyst people so will probably be in a pretty decent state.
