### ISSUE TITLE
Incorrect require_once() for config.php in installation files

### ISSUE THREAD

**Issue by davosmith** [davidpesce/moodle-mod_tincanlaunch#217]
Files:

* db/install.php
* db/uninstall.php

Should not be calling require_once() for config.php, as config.php should have been included by Moodle itself by this point (possibly you should have: `defined('MOODLE_INTERNAL') || die();`   )

Particularly an issue with Totara 13, where this causes a fatal error during install, but not correct for Moodle sites either.

**Comment by davidpesce** [comment]
Sorry for the slow reply. These files aren't customized and therefore not needed. Removed in 758523a8d2e7c359a29e0b90994d0a9351e091f9
