### ISSUE TITLE
Missing $forcedownload argument in tincanlaunch_pluginfile

### ISSUE THREAD

**Issue by ahelton-ips** [davidpesce/moodle-mod_tincanlaunch#218]
I am using the master branch as of 8/3/21 of moodle-mod_tincanlaunch. I am running Moodle 3.8.9.

Ran into an issue when launch a SCORM package via tincanlaunch_pluginfile. The core filelib.php provides an additional $forcedownload parameter to tincanlaunch_pluginfile function. 

It will currently display the following error:
![image](https://user-images.githubusercontent.com/59488858/128227557-2c4c1f22-70ff-45a4-8933-8b9a83de485b.png)

I was able to add the $forcedownload paramater to tincanlaunch_pluginfile, and it resolved the issue.

**Comment by davidpesce** [comment]
Hi @ahelton-ips - sorry for the long reply on this. Thank you for your contribution! It has been approved and merged into master.
