### ISSUE TITLE
tincan launch link not visible

### ISSUE THREAD

**Issue by dogan-guler** [davidpesce/moodle-mod_tincanlaunch#219]
I have Bitnami Moodle installed on aws server and I want to use tincan api to send records to my Learning Locker LRS. I followed the instructions as much as I faced some issues with the integration of tincan plugin. I am stuck at the point that I can attach a tincan launch link from a zip file, and when I manually write the address, I can access it, but the link is not visible on the course page.
I suspect two points maybe related to this problem but I appreciate any comments regarding the problem.

within LRS settings there are no version tab that I can enter the version number as I use xAPI version 1.0.3 ; if there is a place or way that I can change the value it will be fine for me.
the course page gives an error when I activate the developer error on Moodle as:
Warning: Invalid argument supplied for foreach() in /bitnami/moodle/mod/tincanlaunch/view.php on line 127
when I check it in inspection window on the browser/sources, I see no fetch statement.
I really don’t know where to look, any comment will be appreciated.
Thanks
Dogan

**Comment by jramsaybro** [comment]
Hi @dogan-guler & @davidpesce. Wondering if you ever got to the bottom of this issue. My setup is different but I'm experiencing the same basic issue (ie., no launch button, Invalid argument ... view.php on line 127)

**Comment by davidpesce** [comment]
Hello, I'm not sure if this is a valid bug, but this plugin is on our list to get updated and auto-deploying to the Moodle plugin directory. We'll be making sure this works with newer versions of Moodle soon.

**Comment by jramsaybro** [comment]
That's great news - I really appreciate the reply and your efforts, @davidpesce.
