### ISSUE TITLE
Completion How To

### ISSUE THREAD

**Issue by sheetmetaliti** [davidpesce/moodle-mod_tincanlaunch#220]
I am wondering what sort of wizardry is required to get completion tracking to work.  I have tried a variety of things trying to match the object to the activity ID (as the pop-up help states) and nothing seems to work.  I am using the version of the plug-in from the moodle plug-ins page, which appears to be behind this repo.  Latest code seems like it might have some fixes (?).  I am willing to try that, but a clear how-to would be helpful.

**Comment by davidpesce** [comment]
We'll be doing updates to this plugin soon. That said, the version in master is what you're looking for. Hold off on utilizing it as we'll be adding github actions to deploy new releases to the Moodle plugin directory.
