### ISSUE TITLE
xAPI tincan module completion issue

### ISSUE THREAD

**Issue by prasadmunukutlacommlabindia** [davidpesce/moodle-mod_tincanlaunch#221]
Hi,

We are using Tin Can xAPI plugin to launch our course (w.r.t Moodle v3.10.9).

Module is getting completed even if the user attempts / view few slides of the course.

So, how can we enable the completion when the user opens the LAST SLIDE of the course?

Please suggest ASAP.

Regards,
Prasad.

**Comment by davidpesce** [comment]
Hi Prasad - you will need to set the "Track completion by verb" within the Activity Completion. This isn't working 100% with the version that is on the Moodle plugin directory. You will need to use the master branch of this repository until we publish a new version. Expect a new version to be released in the next 2 weeks.
