### ISSUE TITLE
Missing field grade in DB

### ISSUE THREAD

**Issue by henrikthorn** [davidpesce/moodle-mod_tincanlaunch#24]
When trying to edit grade scales, this module creates a fatal error in Moodle. 

URL:
/grade/edit/scale/index.php

Solution:
Add grade-field to table by adding it to the update script. 

Debug info:
Field "grade" does not exist in table "tincanlaunch"

Mere information om denne fejl

Debug info: 
Error code: ddlfieldnotexist
Stack trace:
line 592 of /lib/dml/moodle_database.php: dml_exception thrown
line 1775 of /lib/dml/moodle_database.php: call to moodle_database->where_clause()
line 254 of /mod/tincanlaunch/lib.php: call to moodle_database->record_exists()
line 301 of /lib/grade/grade_scale.php: call to tincanlaunch_scale_used_anywhere()
line 146 of /grade/edit/scale/index.php: call to grade_scale->is_used()

**Comment by garemoko** [comment]
Thanks for raising this. I meant to reply immediately when it came in, but it slipped. 

I appreciate your suggested fix, and I'd be happy with that, but as the module doesn't currently use grades, I wonder if we should instead remove the functions relating to grades from lib.php. That's what the URL and label modules do. 

Potentially we could add some features so that the module does have a grade based on the statements that come in, but that's a bigger chunk of work. 

I'm happy with any of those three solutions if somebody wants to make a pull request.

**Comment by henrikthorn** [comment]
I think we should go for the option with the changes to lib.php instead of the quickfix I suggested. I'll try to get that fix done in this weekend. 

I think it would be great to have grades with this module but as you said, this will require at a lot of work - and I guess a better use case. Let's push wait with that patch.

**Comment by henrikthorn** [comment]
I'll allow myself to restructure your repo a bit in my upcomming pull request, in order to make it easy to install this module in moodle with git clone. I'll simply move the moodle-files into the root of the folder and delete the folder.

**Comment by ntxboi** [comment]
You do realize you're sending this to an entire list of people who have nothing to do with this conversation and not just one person, right?

-----Original Message-----

**Comment by garemoko** [comment]
@ntxboi you can un-watch the github repo at https://github.com/garemoko/moodle-mod_tincanlaunch/

**Comment by davidpesce** [comment]
@henrikthorn Curious on the status of this. Wondering if you're still working on it or if it's up for grabs.

**Comment by henrikthorn** [comment]
@davidpesce  - I did the code change, but haven't had time to do testing. I can supply a patch and you might be able to help testing?

**Comment by davidpesce** [comment]
Can do. Is it just removing this: https://github.com/garemoko/moodle-mod_tincanlaunch/compare/master...henrikthorn:master

**Comment by garemoko** [comment]
Fixed by https://github.com/garemoko/moodle-mod_tincanlaunch/commit/edcce8c3f1caadd7b5c29e1533b15bd01a233ade 

This also changes the required Moodle version to 3.0 as this next release will be for Moodle 3.0.
