### ISSUE TITLE
404 error with function tincanlaunch_get_global_parameters_and_get_state

### ISSUE THREAD

**Issue by davidpesce** [davidpesce/moodle-mod_tincanlaunch#28]
Troubleshooting the LL 490/491 errors and started debugging from the top of launch.php. Getting a 404 error from the following (line 59):

tincanlaunch_get_global_parameters_and_get_state(""http://tincanapi.co.uk/stateapikeys/registrations"");

I'm not sure if this is necessary, but figured I'd flag it for you to take a look at.

**Comment by garemoko** [comment]
404 is expected here and should be handled without issue

**Comment by johnpdonaldson** [comment]
That link appears to be what is keeping this plugin working, at least on my install. I'm running the latest version of this plugin. Why is it pointing to that URL? Should it be getting parameters from my actual LRS?

**Comment by garemoko** [comment]
That's a key. It's not navigating to that url or fetching anything from that url. It's just a unique key.
