### ISSUE TITLE
Endpoint URL should require/add trailing slash

### ISSUE THREAD

**Issue by davidpesce** [davidpesce/moodle-mod_tincanlaunch#32]
Within plugin settings, endpoint URL should require and/or add trailing slash.

As a backup, it may be worth checking for the slash when sending requests to the LRS.

**Comment by davidpesce** [comment]
I'm new to moodle plugins. Where should I put the validation?

**Comment by garemoko** [comment]
https://github.com/garemoko/moodle-mod_tincanlaunch/blob/master/mod_form.php#L90

You might need to google how to actually validate certain characters.

**Comment by davidpesce** [comment]
After a bit of research, that file is when adding the activity to a course. The endpoint text entry is actually hidden. I think I should be looking in settings.php for validation of the endpoint URL. No?

Thinking from a end-user standpoint. Should there be the ability to have multiple endpoints?

My first thought is, yes. If there's an instance where multiple LRS's exist, it'd be nice to have this ability.

For the short term, this may be something that is skipped (and I'm on board with that in the interest of time). 

Thoughts?

**Comment by garemoko** [comment]
Could be a nice advanced (hidden) setting.

**Comment by davidpesce** [comment]
@scara - any pointers on how to validate admin settings for the plugin? I can validate for mod_form.php, but can't seem to find a way to do that for settings.php.

**Comment by scara** [comment]
None at the moment, but will look in my evening (CEST).

**Comment by scara** [comment]
The official documentation can be found here: https://docs.moodle.org/dev/NEWMODULE_Documentation. This will help you in understanding the main difference between the two files, in case you don't know it yet.

That being said, `admin_setting_configtext()` has a fifth param in its ctor that can be used to set the type, e.g. `PARAM_URL`, of the setting: https://github.com/moodle/moodle/blob/6655d6ef6328ddef212385b58cf165062a86f805/lib/adminlib.php#L2113.
You could also write your own regexp pattern validation, by submitting a regexp in the form of a string [`'/write_here_your_regexp_pattern/'`](https://github.com/moodle/moodle/blob/6655d6ef6328ddef212385b58cf165062a86f805/lib/adminlib.php#L2151) as the param type.

HTH,
Matteo

**Comment by davidpesce** [comment]
Thanks! Do you have any examples of it in action? 

I'm not sure it will do what I'd like it to. I'm guessing PARAM_URL would validate that it's a URL and give an appropriate warning if it's not. But I need it to validate that it's a URL and has a trailing slash. And where a regex will fail is on the error response to the user. Can I specify an error message if it doesn't meet the regex?

**Comment by scara** [comment]
No, you can't specify the error message: https://github.com/moodle/moodle/blob/6655d6ef6328ddef212385b58cf165062a86f805/lib/adminlib.php#L2150.

IMHO the trailing slash must be something managed internally through an helper which adds it when missing, w/o warning the user about that missing: it must be an URL and the code will take care of the trailing slash on behalf of the user.

Some examples: https://github.com/moodle/moodle/blob/4cb25b36053f4beda66f153424a4175a24a7e629/mod/scorm/settings.php#L142 and lines below.
To find the few examples using `PARAM_URL` just search for `PARAM_URL));` e.g. https://github.com/moodle/moodle/blob/5f0283046e2711a0e1c5959d674db9cb3facc42c/message/output/airnotifier/settings.php#L28.

**Comment by davidpesce** [comment]
Agreed that the trailing slash should be taken care of internally, but was hoping to do that on user input rather than waiting until the first time it was used. Is there no way to do this?

Something along the lines of:
1. User inputs endpoint and hits save.
2. PARAM_URL validates that it's a URL
3. Check for and add trailing slash (if necessary)
4. Stores in database

The third item is the issue. I had thought I'd be able to override some parent validation/data check, but cannot find it.

**Comment by scara** [comment]
Yep, you can extend the base class and override just `write_setting()` to fix the trailing slash just before calling `return ($this->config_write(...))`, where you can even return your own string message.
Search for `extends admin_setting_configtext` to find some examples e.g.:
- https://github.com/moodle/moodle/blob/6655d6ef6328ddef212385b58cf165062a86f805/lib/adminlib.php#L2365,  which overrides `output_html()`;
- https://github.com/moodle/moodle/blob/6655d6ef6328ddef212385b58cf165062a86f805/lib/adminlib.php#L2405, which overrides `write_setting()`;
- ...
- https://github.com/moodle/moodle/blob/b4fa03606fe82d2303e792168700f5c35625e29b/enrol/ldap/settingslib.php#L54 which overrides `write_setting()` in the LDAP enrollment plug-in.

HTH,
Matteo

**Comment by davidpesce** [comment]
Ahhh, beautiful! This is awesome!! Thank you!!!!

**Comment by davidpesce** [comment]
@scara OK, after digging a bit deeper. I'm wondering if I should override (or overload) the validate function within admin_setting_configtext. Comment at the top of the function reads, "Validate data before storage".

Thoughts?

**Comment by davidpesce** [comment]
Scratch that. After trying that, validate only returns true or an error string. I think you are right about the write_setting() function.

**Comment by davidpesce** [comment]
Fixed. This can be closed.

**Comment by garemoko** [comment]
Tested on master and confirmed.
