### ISSUE TITLE
Include request in debug mode

### ISSUE THREAD

**Issue by davidpesce** [davidpesce/moodle-mod_tincanlaunch#34]
Any objections to adding the actual request sent to the LRS in the moodle debug mode?

**Comment by garemoko** [comment]
Just in the event of an error?

**Comment by davidpesce** [comment]
Yea. Process would be:
1. user can't figure out problem with plugin
2. turns moodle debugging on
3. lrs request appears (along with the other debug info you just put in)

**Comment by garemoko** [comment]
Sounds good

**Comment by garemoko** [comment]
Closing this because it's been 3 years with no PR. PRs welcome though!
