### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by akermen** [davidpesce/moodle-mod_tincanlaunch#39]
When we try to launch the JS Tetris sample from http://tincanapi.com/prototypes, with the scorm's public lrs (http://tincanapi.com/public-lrs/), the plugin reports the following warning and error messages:

Warning: fopen(http://cloud.scorm.com/ScormEngineInterface/TCAPI/public/activities/state?activityId=TETRIS&agent=%7B%22name%22%3A%22demo+demo%22%2C%22mbox%22%3A%22mailto%3Ademo%40momentum-dmt.com%22%2C%22objectType%22%3A%22Agent%22%7D&stateId=http%3A%2F%2Ftincanapi.co.uk%2Fstateapikeys%2Fregistrations): failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request in /var/www/mod/tincanlaunch/locallib.php on line 501
The Learning Record Store is not available. Please contact a system administrator.

![tc1](https://cloud.githubusercontent.com/assets/6176664/6558165/161523d6-c683-11e4-891b-ce4b8dce4daa.png)

The launch urls is, http://cloud.scorm.com/ScormEngineInterface/TCAPI/public/

The same sample app and url pair is working with http://garemoko.github.io/Tin-launcher/ without any issue.

Moodle 2.8.4 (Build: 20150309)
Tin Can Launch Link 1.0 (Build: 2014101300)

**Comment by garemoko** [comment]
Hi @akermen thanks for all the details! The error is in the activity instance settings. You have used an activity id of "TETRIS" whereas the actual activity id of the Tetris prototype is "http://tincanapi.com/JsTetris_TCAPI". 

Activity ids always have to be [IRIs](https://en.wikipedia.org/wiki/Internationalized_resource_identifier). 

Does that solve it?

**Comment by akermen** [comment]
Thank you very much for your prompt reply! Yes it's working right now.
By-the-way, I'm sorry about reporting this not-a-real-issue question here.

**Comment by garemoko** [comment]
No problem! This is the best place to ask questions!
