### ISSUE TITLE
Version.php does not set maturity information or release name. 

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-mod_tincanlaunch#4]
Maturity information ($module->maturity) not found in version.php
Release name ($module->release) not found in version.php

**Comment by scara** [comment]
Hi Andrew,
if you need some refs: http://docs.moodle.org/dev/version.php.

HTH,
Matteo

**Comment by garemoko** [comment]
So here's what I need to add when I get a chance: 

$module->maturity = MATURITY_BETA;
$module->release = '0.2 (Build: 2013072901)';

**Comment by garemoko** [comment]
Done: https://github.com/garemoko/moodle-mod_tincanlaunch/commit/dc9ea224f0cd66a6e96dc2ef09801e75834956f1
