### ISSUE TITLE
Allow upload of Tin Can packages and get data from TinCan.xml file

### ISSUE THREAD

**Issue by nadavkav** [davidpesce/moodle-mod_tincanlaunch#43]
xAPI spec specifies that there should be only one activity with launch URL inside the tincan.xml file.
And it seem more user friendly to ask the user to specify the URL without the specific launch file at the end of the URL and let the module retrieve the tincan.xml and parse it to get both the launch URL and the activity id.
What do you think?

**Comment by garemoko** [comment]
TBH I thought this was already listed as an issue! Completely agree that a very nice feature would be to allow an uploaded tincan.xml file as another option instead of completing the settings manually.

**Comment by nadavkav** [comment]
Great. I will upload a fix.

**Comment by agricolan** [comment]
This would be a much-appreciated feature for users with little technical knowledge of IRIs as it would mimic how one sets up a tin can course in Scormcloud using the tincan.xml

**Comment by garemoko** [comment]
Might also be a nice feature to validate that the xml file contains an IRI and not some invalid activity id, to avoid people thinking they have uploaded a valid file and then find the plugin doesn't work.

**Comment by nadavkav** [comment]
Checkout this PR https://github.com/garemoko/moodle-mod_tincanlaunch/pull/54
It's an initial concept. Please feedback me.

**Comment by nadavkav** [comment]
@garemoko , Do you mean checking that the Activity's ID is a valid IRI by testing it using regex (example: http://stackoverflow.com/questions/161738/what-is-the-best-regular-expression-to-check-if-a-string-is-a-valid-url) Or actually trying to figure it out by sending an HTTP GET request to the launch property and make sure we get 200 return value?

**Comment by garemoko** [comment]
Testing it's valid using regex or similar. Thanks!

**Comment by nadavkav** [comment]
Great. I will make it vegan friendly :smile:

**Comment by garemoko** [comment]
This is done in the latest commit. Testers welcome @nadavkav @davidpesce!

There's two obvious bugs in the file upload: 
1. The language string doesn't seem to be pulling through (possibly I just need to bump the version number).
2. The file upload doesn't show files that you uploaded last time you editted the settings. I'm not sure there's any way to remove uploaded zip packages either, so the moodledata directory is just going to get more and more bloated.

**Comment by garemoko** [comment]
I'm also not doing any validation at all. It's pretty rough and ready right now, but it works.

**Comment by scara** [comment]
Not having the time to run the code but:
1. https://github.com/garemoko/moodle-mod_tincanlaunch/commit/12a18c988ee0fab089c9c3969a0428784eee3610#diff-828043dc9f8d10ccd58ff8b96297794fR114: is  `scorm` a "typo",  `tincanlaunch` seems more appropriate here;
2. https://github.com/garemoko/moodle-mod_tincanlaunch/commit/12a18c988ee0fab089c9c3969a0428784eee3610#diff-828043dc9f8d10ccd58ff8b96297794fR184 should remove all the files previously uploaded;
3. yes, bumping the _module version_ is required to invalidate the caches and reloading the strings too.

HTH,
Matteo

**Comment by garemoko** [comment]
@scara thanks for this. The SCORM reference is definitely an error. I actually need to do a bunch of refactoring to bring the add module function into line with the update module function. Right now I don't believe the file upload will work for new modules.

**Comment by garemoko** [comment]
I did a bunch of testing, fixes and code tidying this morning. Seems to be working solidly now so I'm calling this done.
