### ISSUE TITLE
Multi language activity

### ISSUE THREAD

**Issue by akermen** [davidpesce/moodle-mod_tincanlaunch#45]
Is it possible to pass user's language preferences to tincan activity as URL parameters ?
so activity can switch languages based on user preferences.

**Comment by davidpesce** [comment]
I don't believe it passes the lang preferences as a URL parameter, but it does pass it in the JSON that is sent to the LRS. 

Does that help?

**Comment by akermen** [comment]
An activity reading user's language preferences from lrs is plausible but seems to be more like a hack, I think. 

Right now I'm checking a way to read moodle's config and create a script which will act like a proxy adding language preferences to the launch url and redirect to actual activity. But still this one is not ideal solution, because a case where an activity is stored on a different server/domain, this one becomes unpractical in every way.

**Comment by garemoko** [comment]
We're following the draft CMI5 specification for how we handle it: https://github.com/AICC/CMI-5_Spec_Current/blob/master/cmi5_runtime.md#110-xapi-agent-profile-data-model

It's not a hack, it's (or will be) an industry standard way of doing it.

**Comment by akermen** [comment]
Sorry It appeared to me like it was a feature and missing, and did not know that's the part of the spec.
Thank you very much both of you for your prompt replies.

**Comment by garemoko** [comment]
No problem! Let us know if you have more questions!
