### ISSUE TITLE
Enhancement - Override default (global) LRS settings in each activity

### ISSUE THREAD

**Issue by davidpesce** [davidpesce/moodle-mod_tincanlaunch#46]
Starting a new issue to discuss this.

I'm creating a new table (tincanlaunch_lrs), linkable to tincanlaunch via tincanactivityid. This table will store lrs endpoint, auth, login, pass, and version. Mostly because if this plugin sticks around for awhile, we may get a request to add multiple LRS details at the global level and then activities can pick and choose from a list (rather than typing it out every time).

What I'm stumbling on is duration. It seems like duration should be at the activity level. This activity takes x amount of time to complete. Yes, it will inherit the global unless overridden. But I think it should be stored in the tincanlaunch table rather than the tincanlaunch_lrs table.

Thoughts?

**Comment by garemoko** [comment]
It could be related to a specific LRS e.g. if one LRS has stricter security. Does that help?

**Comment by davidpesce** [comment]
Should we then have a field within tincanlaunch called activityduration and then another within the tincanlaunch_lrs table that has lrsduration?

I may be over-thinking this...

**Comment by garemoko** [comment]
The duration field is the length of time an LRS keeps the activity provider's session active. 

Having different durations for different LRS and different activities could be very helpful, but could get complicated fast! You'll need to think about it carefully. For most users they will want one single duration setting.

**Comment by davidpesce** [comment]
Looking at [#L553](https://github.com/garemoko/moodle-mod_tincanlaunch/blob/master/lib.php#L553), is there ever an instance where multiple records will be retrieved? If not, do you mind me changing it to:

```
$DB->get_record();
```

**Comment by garemoko** [comment]
TBH I'm not sure what that code does. If your change doesn't break anything, go ahead!

**Comment by davidpesce** [comment]
After a bit more digging, it does look like it needs to pull additional rows. The config_plugins table has each value stored in a row.

**Comment by garemoko** [comment]
I like the global settings added in #44 and they appear to work. (yay!)

I don't like that duration and the LRS settings are both unlocked by the same checkbox. I believe that the most common scenario for people using integrated LRS auth (which is the only setting that duration is relevant for) is that the duration will be different per activity but the LRS settings will be central. This setting should therefore be unlocked individually from the other LRS settings. 

I think we also need to be clearer on what duration does within the instance settings: "Used with 'LRS integrated basic authentication'. Requests the LRS to keep credentials valid for this number of minutes."
