### ISSUE TITLE
Version field should be renamed "launch version" and used accordingly.

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-mod_tincanlaunch#48]
The plugin doesn't in fact support 0.9 - it breaks when you try. Instead, we should use 1.0.2 for all communication between Moodle and the LRS and only use the version setting when building the launch URL.

**Comment by davidpesce** [comment]
Are there instances when the LRS version would be out of sync with the "launch version"?

**Comment by davidpesce** [comment]
Seeing as I'm already in here. Should I remove version from the admin settings?

**Comment by garemoko** [comment]
The setting is good, just needs renaming to "launch version" and only using when building the launch URL

**Comment by garemoko** [comment]
Sorry, Im wrong. its not used in the launch url. We can kill the setting and always use 1.0.2

**Comment by davidpesce** [comment]
May still be worth storing in the admin settings... or no?

**Comment by garemoko** [comment]
No, it can be hard coded or better, stored as a hard coded constant.

**Comment by davidpesce** [comment]
Fixed. This can be closed.
