### ISSUE TITLE
Move to PHP5.4, use TinCanPHP and split launch functions out into separate library

### ISSUE THREAD

**Issue by davidpesce** [davidpesce/moodle-mod_tincanlaunch#49]
I found this note within locallib.php

```
//Note: when Moodle moves to PHP 5.4 as a minimum this can be done more smoothly using http_build_query.
//See 'PHP_QUERY_RFC3986' at http://php.net/manual/en/function.http-build-query.php
```

Since moodle 2.7 and newer has a php 5.4.4 requirement and we have a branch for earlier moodle release, does it make sense to update this?

**Comment by garemoko** [comment]
Yes. 

Further, if we are requiring PHP 5.4, we should use TinCanPHP: https://github.com/rusticisoftware/TinCanPHP

**Comment by garemoko** [comment]
Also, pull the generic Tin Can launch functions that could be used with any PHP platform into a separate library.

**Comment by garemoko** [comment]
TinCanPHP has been added and implemented.

I'm not going to pull our the generic launch functions as there's not enough of them to make it worthwhile.
