### ISSUE TITLE
Activity Tin Can Launch Link "Save" Button

### ISSUE THREAD

**Issue by akermen** [davidpesce/moodle-mod_tincanlaunch#50]
When the version field left empty at the LRS Settings form:
![tc-1](https://cloud.githubusercontent.com/assets/6176664/6778868/29f8529c-d15f-11e4-9da0-3bd6c9e91969.png)

activity create or edit form's save button does seem to have no effect and gives no feedback,
can't save unless the LRS version field set:
![tc-2](https://cloud.githubusercontent.com/assets/6176664/6778869/2a32686a-d15f-11e4-8f6b-b7049af1100e.png)

Moodle 2.8.5+ (Build: 20150313)
Tin Can Launch Link 1.0 (Build: 2014101300)
Safari Version 8.0.4 (10600.4.10.7) on OSX 10.10.2

**Comment by garemoko** [comment]
Thanks for raising this. 

We're actually going to remove the version field altogether (#48), which hopefully should also resolve this issue.

**Comment by davidpesce** [comment]
This is fixed with PR #56.

**Comment by davidpesce** [comment]
Fixed. This can be closed.
