### ISSUE TITLE
SCORMCloud LRS 400 bad request

### ISSUE THREAD

**Issue by davidpesce** [davidpesce/moodle-mod_tincanlaunch#51]
For some reason I'm getting a 400 bad request when attempting to use SCORMCloud instead of LL. Can you check this?

**Comment by garemoko** [comment]
When are you getting the error? Any message?

**Comment by davidpesce** [comment]
tincanlaunch_get_state (locallib.php)

Here's the decoded error:

```
Warning: fopen(https://cloud.scorm.com/tc/scrubbed/activities/state?activityId=http://scrubbed/tc_golf/index.html&agent={"name":"Admin User","mbox":"mailto:scrubbed","objectType":"Agent"}&stateId=http://tincanapi.co.uk/stateapikeys/registrations): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found in Z:\xampp\apps\moodle\htdocs\mod\tincanlaunch\locallib.php on line 501
```

**Comment by davidpesce** [comment]
Ha, nevermind! I was somehow ignoring the "New Attempt" link below this...

**Comment by davidpesce** [comment]
The good news is that I'm very close to having global and activity-specific LRS settings! Along with a few other issues.
