### ISSUE TITLE
Typo - tincanlaunchlrauthentication

### ISSUE THREAD

**Issue by davidpesce** [davidpesce/moodle-mod_tincanlaunch#52]
within the admin settings (and throughout the code), "tincanlaunchlrauthentication" appears to have a typo. I believe it should be: "tincanlaunchlrSauthentication" (capital S used for visual. propose lowercase in actual fix).

**Comment by garemoko** [comment]
+1

**Comment by davidpesce** [comment]
Odd, I can't seem to find anything in the way of documentation/forums on making changes to an existing plugin's admin settings. Any pointers?

**Comment by davidpesce** [comment]
I did a search and replace for all instances to see what happens. Nothing changes within the config_settings table until you re-save the tincanlaunch admin settings. It then adds another row in config_plugins that shows the correct spelling.

Before and after the re-save, the plugin continues to work. However, the original misspelled version is in the config_plugins table. I'd think there would be a graceful way to remove it. Graceful, meaning, not having to write a sql query that does the job.

Which brings up another point. We'll need to remove the tincanlaunchversion entry from the config_plugins table as well...

**Comment by garemoko** [comment]
Thats a Moodle forum question - I'm not sure.

**Comment by davidpesce** [comment]
Unfortunately, my questions are never answered on the Moodle forums. I stopped asking. :(

All-in-all, it doesn't impact the plugins performance to have unused settings. But in the effort of keeping things tidy, I'd like to get it removed.

I'll play around with removing it via the upgrade.php file. I think that's the only way it'll make sense to future users.

**Comment by scara** [comment]
@davidpesce Where did you post your question? I still need to manage about the past 2 days email backlog from Moodle.org (really a huge amount :astonished:) and I'll reply to you, there, in the next evenings.

**Comment by davidpesce** [comment]
Fixed. This can be closed.
