### ISSUE TITLE
text fixes from PR 44

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-mod_tincanlaunch#55]
See https://github.com/garemoko/moodle-mod_tincanlaunch/pull/44#issuecomment-87986677

**Comment by davidpesce** [comment]
Fixed. This can be closed.

**Comment by garemoko** [comment]
Still need to rename "Advanced" to "LRS settings". Also related, these settings should be closed by default.

**Comment by davidpesce** [comment]
You may need to purge your cache. LRS Settings is there. But it is open by default. I can adjust that in the next push.

**Comment by garemoko** [comment]
I stand corrected: https://github.com/garemoko/moodle-mod_tincanlaunch/blob/master/lang/en/tincanlaunch.php#L72
