### ISSUE TITLE
The Tin Can launch link redirects to all courses...

### ISSUE THREAD

**Issue by openflips** [davidpesce/moodle-mod_tincanlaunch#6]
Hi,

I'm not sure I set up my course right.

I downloaded the golf example from the tin can official page and uploaded it to my server.

I signed up to Wax LRS free dev account. 

I've properly installed this Moodle plugin.

I've created a course and a Tin Can Launch link : 

I don't know what to put for Activity ID but I've tried several things (url of activity, custom string, url of original activity on tincanapi.com...) Please advise me for that.

The End point is directly given by Wax LRS so no problem.

The login / password fields : I created in Wax both Basic and OAuth credentials and tried them both.

I left the 1.0.0 version without knowing which one is really used (LRS or Activity...?).

Please give me hints to find out why I'm redirected to all courses when I set up this great plugin / Tin Can launch link.

Thanks,
flips

**Comment by garemoko** [comment]
Hi, 
Thanks for trying this out. 

The activity id should be set somewhere in the golf example itself, but for now just  put any url - it's fine for testing. 

I think maybe you've entered the Launch URL wrong. Can you try navigating to that URL outside of Moodle and see if it works? It should still launch the golf example, although the tracking won't work of course. 

Also try entering "http://tincanapi.co.uk as the Launch URL - this should open up my website, which isn't a Tin Can activity but will show that the launch link is working. 

If none of that helps you work things out, please let me know the results and take as many screenshots as you can ;-)

Let me know how you get on.

Andrew

**Comment by openflips** [comment]
Hi Andrew, thanks for your help.

Activity id is right. Launch URL seems fine but which file we should link to ? index.html, launch.html, tincan.xml ....

I tried all of them. The activity is the Golf example from the official tin can website.
Putting your website as Launch URL doesn't work either, I'm still redirected to all courses...

No screenshot to take so far... My course fields? I wrote you what I put. I click on the launch link in the moodle course and it takes me to all courses...

**Comment by garemoko** [comment]
Hi, 
Are you using Moodle 2.5?

Try these exact settings: http://screencast.com/t/a7VqeKoV

Andrew

**Comment by garemoko** [comment]
By the way, what web browser are you using?

**Comment by garemoko** [comment]
By the way 2: This is what you should see when you use those settings: http://screencast.com/t/JVXBZnCvJGi

**Comment by openflips** [comment]
Yes I'm using Moodle 2.5.2. No success with your settings, I still get redirected to all courses...

Is the link created well : mod/tincanlaunch/view.php?id=7 ?

Should I reinstall Moodle and try again? That might be for tomorrow.

I use Firefox/Ubuntu and also tried Chrome/Windows 7

I will provide you with access to this Moodle but I have to give up for today.

Thanks a lot, hope we get it working soon.
flips

**Comment by garemoko** [comment]
I'm running out of ideas. I can't think how it's possible it redirects to all courses with those settings. I think I'd need some screenshots or a video show me exactly what you are doing to try and work it out. Or access to your Moodle. 

Andrew

**Comment by garemoko** [comment]
Do you get as far as a screen that looks like this: http://screencast.com/t/oIzxBig5x5 

If not, have you tried turning debug mode on your Moodle and see if you get any errors?

**Comment by openflips** [comment]
No I didn't get as far :(

I turned on the debug mode but nothing is displayed.

I will reinstall both moodle and the plugin and give you access.

If you are using a Moodle version prior to 2.5.2, it might be the issue...

Thanks for your time, I'll get back to you soon.
flips

**Comment by garemoko** [comment]
I'm using Moodle 2.5.1+ (Build: 20130726) so that could be it. I'm off to bed now and not available tomorrow but I'll try to upgrade another day and see if I can replicate the problem.

**Comment by garemoko** [comment]
How did you install - did you put the plugin in the folder or use the new install plugin features built into Moodle?

**Comment by garemoko** [comment]
You could also try the previous commit of the plugin. I made a fix for the plugin validator that perhaps I didn't test well enough:

https://github.com/garemoko/moodle-mod_tincanlaunch/archive/05c4402060e47d925354a0820fd9fb5794632129.zip

**Comment by garemoko** [comment]
Hi, 
I've upgraded my Moodle to 2.5.2+ (Build: 20130913) and I'm using the latest version of this plugin from Github. It all still works absolutely fine for me. 

I'm running the Moodle on Windows 7 with XAMPP if that helps. PHP Version 5.3.8.

Andrew

**Comment by openflips** [comment]
Hi Andrew,

I installed the plugin using the new install plugin features built into Moodle.

I will reinstall Moodle and install the plugin from Github but probably tomorrow.

I used a fresh install of Moodle 2.5.2 so my guess is that you are correctly thinking of the plugin installator...

Thanks.
flips

**Comment by openflips** [comment]
Hi Andrew,

fresh Moodle 2.5.2 install with manual install of the plugin downloaded from Gihhub, it works with your settings.

I assume there is an issue when installing the plugin using the built-in installer...

Thanks for your help, I'm happy to keep testing.
flips
