### ISSUE TITLE
open tincan activity from the mobile application

### ISSUE THREAD

**Issue by akermen** [davidpesce/moodle-mod_tincanlaunch#60]
Is it possible to launch tincan activity from official moodle mobile application (https://docs.moodle.org/28/en/index.php?title=Moodle_Mobile), assuming content is compatible with mobile platform ?

**Comment by davidpesce** [comment]
I've never tried this, but I don't see why it wouldn't work. That being said, I don't believe it would support asynchronous communications. Once you lose an internet connection or close the browser, you'll stop sending statements.

**Comment by akermen** [comment]
Actually I already tried with the golf example (form http://tincanapi.com/download-prototypes/) as an course tincan activity. The moodle mobile application opened the moodle's original web login page in a web-view when touched from course contents. When logged in the rest is same with opening from a mobile browser.

**Comment by garemoko** [comment]
Great!
