### ISSUE TITLE
Change 'Tin Can' to xAPI

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-mod_tincanlaunch#74]
This isn't one that I'm going to put the effort into changing myself, but if somebody wants to submit a PR, I'll review and merge it.

**Comment by dwainbeck** [comment]
Can you clarify some more Andrew, are you referring to everywhere in the code where it says 'Tin Can', or 'TinCan', or 'tin can', or tincan, that should be changed to 'xAPI'?

**Comment by garemoko** [comment]
Yes, but there also needs to be some clever backwards compatibility stuff so people can upgrade smoothly. It may or may not be possible.

**Comment by dwainbeck** [comment]
This is the statement saved in the LRS;

{
    "version": "1.0.0",
    "actor": {
        "objectType": "Agent",
        "name": "LMS User",
        "mbox": "mailto:admin@email.com"
    },
    "verb": {
        "id": "http://adlnet.gov/expapi/verbs/experienced"
    },
    "context": {
        "registration": "81203947-e736-4f12-9b04-999d4348233d",
        "contextActivities": {
            "grouping": [
                {
                    "objectType": "Activity",
                    "id": "http://unique_url"
                }
            ],
            "parent": [
                {
                    "objectType": "Activity",
                    "id": "http://unique_url2"
                }
            ]
        }
    },
    "object": {
        "objectType": "Activity",
        "id": "http://unique_url/6Jv8029UFie",
        "definition": {
            "name": {
                "und": "Audio Controls"
            },
            "type": "http://adlnet.gov/expapi/activities/module",
            "description": {
                "und": "Audio Controls"
            }
        }
    },
    "id": "f6137dc1-4fc9-4275-bb9e-ac475e01cdd1",
    "authority": {
        "objectType": "Agent",
        "name": "API Client",
        "mbox": "mailto:hello@learninglocker.net"
    },
    "stored": "2016-12-06T16:37:08.162200+00:00",
    "timestamp": "2016-12-06T16:37:08.162200+00:00"
}

No matter the changes I make in locallib.php the statement does not add the new field.
