### ISSUE TITLE
File not displayed in file picker when editing settings

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-mod_tincanlaunch#79]
1. Upload a zip package. An icon representing the file is shown in the file picker. 
2. Save settings, then edit the module. The file picker shows no files. 

I spent a while looking at this one and couldn't see where the issue lies. The file is successfully uploaded and unzipped, and the default value of the file picker is getting set. I don't plan to spend any more time on it unless somebody can give me some direction. 

The file picker for the Resource module does not display this behaviour.

**Comment by mediabounds** [comment]
It seems like this issue was fixed with this commit: https://github.com/garemoko/moodle-mod_tincanlaunch/commit/0ea0f1a70e43a3841ec8f433c186ede3c4dbbc31

The `$defaultvalues['packagefile']` is now correctly set when loading the form.

**Comment by garemoko** [comment]
Oh good. Thanks!

**Comment by garemoko** [comment]
This is not in fact fixed. 

I think the issue might be here: https://github.com/garemoko/moodle-mod_tincanlaunch/blob/master/lib.php#L345-L346

**Comment by mediabounds** [comment]
FWIW, in our environment, the current version of the plugin doesn't display the behavior described above (though the previous version did).

**Comment by garemoko** [comment]
Interesting, thanks!

I *am* able to replicate the issue on my localhost Moodle.

**Comment by garemoko** [comment]
Can't replicate.
