### ISSUE TITLE
TinCanPHP missing from package

### ISSUE THREAD

**Issue by hallshouse** [davidpesce/moodle-mod_tincanlaunch#80]
Tried to install the plugin as was, but found the TinCanPHP folder was empty.
After correcting that, then configuring the plugin in my Moodle 3.0 installation I setup a course that works everywhere else (including in my TIN CAN Manager WP Plugin).

I'm running it with LearningLocker 1.11.0
NOTE: I expect the issue may be related to the %40 being output in the email address, but I'm no expert with this plugin.
Side Note: I also installed the TinCan Learnerstream plugin and that works fine in Moodle.

I launched the course in Moodle and received the following output:

The Learning Record Store is not available. Please contact a system administrator. If you are the system administrator, go to Site admin / Development / Debugging and set Debug messages to DEVELOPER. Set it back to NONE or MINIMAL once the error details have been recorded.

Error attempting to set learner preferences to Agent Profile API.
object(TinCan\LRSResponse)#330 (3) {
  ["success"]=>
  bool(false)
  ["content"]=>
  string(3889) "{"error":true,"success":false,"message":"Unauthorized request.","code":401,"trace":"#0 \/var\/www\/learninglocker\/app\/locker\/repository\/Document\/EloquentDocumentRepository.php(473): Locker\Repository\Document\EloquentDocumentRepository->filterScopes(Array, 'profile', false)\n#1 \/var\/www\/learninglocker\/app\/locker\/repository\/Document\/EloquentDocumentRepository.php(100): Locker\Repository\Document\EloquentDocumentRepository->storeAgentDoc(Array, Array, '2015-11-28T14:1...', 'PUT')\n#2 \/var\/www\/learninglocker\/app\/controllers\/xapi\/DocumentController.php(97): Locker\Repository\Document\EloquentDocumentRepository->store(Array, 'agentProfile', Array, '2015-11-28T14:1...', 'PUT')\n#3 \/var\/www\/learninglocker\/app\/controllers\/xapi\/DocumentController.php(116): Controllers\xAPI\DocumentController->store()\n#4 \/var\/www\/learninglocker\/app\/controllers\/xapi\/BaseController.php(44): Controllers\xAPI\DocumentController->update()\n#5 [internal function]: Controllers\xAPI\BaseController->selectMethod()\n#6 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Controller.php(231): call_user_func_array(Array, Array)\n#7 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('selectMethod', Array)\n#8 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\xAPI\AgentController), Object(Illuminate\Routing\Route), 'selectMethod')\n#9 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(962): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\xAP...', 'selectMethod')\n#10 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()\n#11 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Route.php(109): call_user_func_array(Object(Closure), Array)\n#12 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(1028): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))\n#13 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(996): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))\n#14 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Application.php(776): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))\n#15 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Application.php(746): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))\n#16 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Session\/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)\n#17 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Cookie\/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)\n#18 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Cookie\/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)\n#19 \/var\/www\/learninglocker\/vendor\/stack\/builder\/src\/Stack\/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)\n#20 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Application.php(642): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))\n#21 \/var\/www\/learninglocker\/public\/index.php(49): Illuminate\Foundation\Application->run()\n#22 {main}"}"
  ["httpResponse"]=>
  array(4) {
    ["status"]=>
    int(401)
    ["headers"]=>
    array(2) {
      ["contentType"]=>
      string(16) "application/json"
      ["date"]=>
      string(29) "Sat, 28 Nov 2015 14:12:54 GMT"
    }
    ["_content"]=>
    string(3889) "{"error":true,"success":false,"message":"Unauthorized request.","code":401,"trace":"#0 \/var\/www\/learninglocker\/app\/locker\/repository\/Document\/EloquentDocumentRepository.php(473): Locker\Repository\Document\EloquentDocumentRepository->filterScopes(Array, 'profile', false)\n#1 \/var\/www\/learninglocker\/app\/locker\/repository\/Document\/EloquentDocumentRepository.php(100): Locker\Repository\Document\EloquentDocumentRepository->storeAgentDoc(Array, Array, '2015-11-28T14:1...', 'PUT')\n#2 \/var\/www\/learninglocker\/app\/controllers\/xapi\/DocumentController.php(97): Locker\Repository\Document\EloquentDocumentRepository->store(Array, 'agentProfile', Array, '2015-11-28T14:1...', 'PUT')\n#3 \/var\/www\/learninglocker\/app\/controllers\/xapi\/DocumentController.php(116): Controllers\xAPI\DocumentController->store()\n#4 \/var\/www\/learninglocker\/app\/controllers\/xapi\/BaseController.php(44): Controllers\xAPI\DocumentController->update()\n#5 [internal function]: Controllers\xAPI\BaseController->selectMethod()\n#6 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Controller.php(231): call_user_func_array(Array, Array)\n#7 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/ControllerDispatcher.php(93): Illuminate\Routing\Controller->callAction('selectMethod', Array)\n#8 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/ControllerDispatcher.php(62): Illuminate\Routing\ControllerDispatcher->call(Object(Controllers\xAPI\AgentController), Object(Illuminate\Routing\Route), 'selectMethod')\n#9 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(962): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Controllers\xAP...', 'selectMethod')\n#10 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()\n#11 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Route.php(109): call_user_func_array(Object(Closure), Array)\n#12 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(1028): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))\n#13 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(996): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))\n#14 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Application.php(776): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))\n#15 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Application.php(746): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))\n#16 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Session\/Middleware.php(72): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)\n#17 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Cookie\/Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)\n#18 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Cookie\/Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)\n#19 \/var\/www\/learninglocker\/vendor\/stack\/builder\/src\/Stack\/StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)\n#20 \/var\/www\/learninglocker\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Application.php(642): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))\n#21 \/var\/www\/learninglocker\/public\/index.php(49): Illuminate\Foundation\Application->run()\n#22 {main}"}"
    ["_metadata"]=>
    array(10) {
      ["wrapper_data"]=>
      array(12) {
        [0]=>
        string(25) "HTTP/1.0 401 Unauthorized"
        [1]=>
        string(35) "Date: Sat, 28 Nov 2015 14:12:54 GMT"
        [2]=>
        string(29) "Server: Apache/2.4.7 (Ubuntu)"
        [3]=>
        string(19) "Vary: Authorization"
        [4]=>
        string(35) "X-Powered-By: PHP/5.5.9-1ubuntu4.14"
        [5]=>
        string(39) "Cache-Control: private, must-revalidate"
        [6]=>
        string(16) "pragma: no-cache"
        [7]=>
        string(11) "expires: -1"
        [8]=>
        string(411) "Set-Cookie: laravel_session=eyJpdiI6IkdCZWpTTmt2amhmMWg0d3k0YW9rbkY5dGlUY01jQlV4cWFPVDRHMEFCd3c9IiwidmFsdWUiOiJ4MTgxdGdOR1doU29sWFg4R21LcDdobkIwUnBcL3BMWGlQODZLMlwvMXh4dm0yczRpNHpqMVluQkJnaWFzSURTTFZHSXpIMWVvTFFLdmw2bklNalwvXC9vQmc9PSIsIm1hYyI6ImUxYjk4MTNhOWE5ODMzYmNhNDdiM2ZhMzViNzViZTNjYWY4YTgwYWJmZWE0ZDdlZThkOTFiMzQ5ODFhNjBkZGYifQ%3D%3D; expires=Sat, 28-Nov-2015 16:12:54 GMT; Max-Age=7200; path=/; httponly"
        [9]=>
        string(20) "Content-Length: 3889"
        [10]=>
        string(17) "Connection: close"
        [11]=>
        string(30) "Content-Type: application/json"
      }
      ["wrapper_type"]=>
      string(4) "http"
      ["stream_type"]=>
      string(14) "tcp_socket/ssl"
      ["mode"]=>
      string(2) "rb"
      ["unread_bytes"]=>
      int(2183)
      ["seekable"]=>
      bool(false)
      ["uri"]=>
      string(220) "http://lrs.learning-templates.com/data/xAPI/agents/profile?agent=%7B%22objectType%22%3A%22Agent%22%2C%22name%22%3A%22Dennis%20Hall%22%2C%22mbox%22%3A%22mailto%3Adhall%40videotron.ca%22%7D&profileId=CMI5LearnerPreferences"
      ["timed_out"]=>
      bool(false)
      ["blocked"]=>
      bool(true)
      ["eof"]=>
      bool(false)
    }
  }
}

**Comment by garemoko** [comment]
Thanks for reporting. I published the release using the new Moodle plugins directory github integration. Very smooth to use but I guess it fails to handle submodules. 

The error you shared (code 401) means that the LRS rejected the credentials you used. Check that you entered them correctly.

**Comment by hallshouse** [comment]
Hi Andrew:

The LRS Creds are correct.

They are exactly the creds I use in my Tin Can Manager Plugin in WordPress. I copied them from there.

Here are the creds:

Endpoint: http://lrs.learning-templates.com/data/xAPI/

LRS Username: cedbf0f33b20c9661b24dea30c593d23871229b9

LRS Password: 4a5816a331c7d7b7da1cdd1ea2d0c9711be92989

The only thing I see is that the %40 is in the launch URL email address, whereas in all my other work, the @ not been encoded (it has remained @) in the resulting URL query.

I agree the 401 error is normally an issue when the launch string contains incorrect info, however, I usually get a 400 error when I cannot connect to the LRS.

Also, is the plugin requiring I enter a protocol (like http://) in front of the Activity ID (just curious)?

I tried with and with the protocol and it still did not work.

Best Regards,

Dennis Hall

phone_sm 450.461.3633

favicon http://products-and-services.ca/ Products and Services.Canada  LT_Logo_sm-32x30  http://learning-templates.com/ Learning Templates.com

**Comment by garemoko** [comment]
Thanks for checking those. Do you mind generating a fresh set of credentials in learning locker and using those and if those don't work, test with another lrs such as SCORM cloud. If the issue is the format of the email then I'd expect error code 400 or perhaps 403.

**Comment by garemoko** [comment]
Also, I can't help but notice that your username is 1 character shorter than the password. Are you sure you didn't miss a character off the beginning or end?

**Comment by garemoko** [comment]
@hallshouse I have tested your credentials with http://adlnet.github.io/xapi-lab/ and confirmed that they work with the statement API but the Agent Profile API returns 401. I'm therefore concluding that there's a bug in the version of Learning Locker that you are using. 

Best I can suggest is to either [raise an issue for Learning Locker](https://github.com/LearningLocker/learninglocker/issues) or use [a different Learning Record Store](http://watershedlrs.com/request-demo/). 

Please leave this issue open whilst I look into the missing TinCanPHP thing.

**Comment by hallshouse** [comment]
Hi Andrew:

Thanks for getting back with so much detail.

Regarding my username; what I provided is correct (to the character)

I will test this with SCORM Cloud.

I’ll take a closer look at the Agent API code in LL and if I can correct it, I’ll submit a PR to them, else I’ll open a ticket with them.

Have a great Sunday.

Best Regards,

Dennis Hall

phone_sm 450.461.3633

favicon http://products-and-services.ca/ Products and Services.Canada  LT_Logo_sm-32x30  http://learning-templates.com/ Learning Templates.com

**Comment by garemoko** [comment]
Released new version including tincanphp by hand
