### ISSUE TITLE
Plus symbol breaks basic auth

### ISSUE THREAD

**Issue by BatteryAcid** [davidpesce/moodle-mod_tincanlaunch#81]
Hello,

I have a Captivate course uploaded using the tincanlaunch plugin.  After launching the course, any request to the LRS (whether it's lrs.adlnet.gov or my local deployment of LearningLocker) returns a similar error: 

> "The format of the HTTP Basic Authorization Header value is incorrect"
> 
> referer url:
>  http://localhost:8888/moodle30/pluginfile.php/44/mod_tincanlaunch/content/multiscreen.html?endpoint=https%3A%2F%2Flrs.adlnet.gov%2Fxapi%2F&auth=**Basic+eGFwaS10b29sczp4YXBpLXRvb2xz**&actor=%7B%7D&registration=b3249322-c0a5-4fb6-93d0-c74f8736a120
> 
> request url: 
> https://lrs.adlnet.gov/xapi/statements?statementId=38e35fd2-6938-4598-af4a-96760be275b2

If I replace the "+" with "%20" in the "auth" query param, it seems to work (or just reveal the next problem - see #82).

**Comment by garemoko** [comment]
Hi Bruce, 
Thanks for reporting these. I think they are two separate issues, so I'm going to move the agent thing to a new ticket.

**Comment by garemoko** [comment]
I can replicate this issue on my localhost.

Next steps:
- check if "+" is rejected by other LRSs
- figure out if this is a bug in this plugin or ADL LRS
- track down where this is occurring in the plugin code

**Comment by garemoko** [comment]
Testing in Chrome with the golf example and Watershed LRS, the plus symbol does not cause a problem. @BatteryAcid what content are you using?

**Comment by BatteryAcid** [comment]
The content is a course that we created internally using Captivate.

**Comment by garemoko** [comment]
Hm, that's interesting because Captivate uses TinCanJS too. I tested taking the endpoint and auth details from your query string and plugging them into the golf prototype and they work, so it's not an LRS issue, definitely an incompatibility with the content or the web browser. 

Can you share the zip file? What web browser are you using? Can you share the full details of the HTTP request that's failing?

I'm reluctant to fix because based on some quick Googling, + is the right character to encode query string params with, because I haven't been able to replicate myself, and because I'm using the standard PHP http_build_query function (line 152 of locallib.php).

**Comment by garemoko** [comment]
Note: This could be fixed by adding an additional parameter to http_build_query "PHP_QUERY_RFC3986" as a new line 165 in locallib.php. I just want to confirm if it **should** be fixed. 

```
    $rtnString = $tincanlaunch->tincanlaunchurl."?".http_build_query(
        array(
            "endpoint" => $url,
            "auth" => "Basic ".$basicauth,
            "actor" => tincanlaunch_myJson_encode(
                tincanlaunch_getactor($tincanlaunch->id)->asVersion(
                    $tincanlaunchsettings['tincanlaunchlrsversion']
                )
            ),
            "registration" => $registrationuuid
        ),
        '',
        '&',
        PHP_QUERY_RFC3986
    );
```

(tested and confirmed that works)

**Comment by garemoko** [comment]
For the sake of not having to get all the code out again, I've commit this fix as if it's a problem in Captivate and presumably a commonly used browser, I'm going to end up having to do that anyway.  I would still like to get to the bottom of where the issue lies before pushing a new release though.

**Comment by BatteryAcid** [comment]
I've tested this in both Chrome and Firefox on a macbook pro.  I'll have to get back to you on sending our zip file.  Below are the details from one of the failed requests.  Let me know if you need any other info.

**General**
Request URL:https://lrs.adlnet.gov/xapi/statements
Request Method:POST
Status Code:401 UNAUTHORIZED
**Response Headers**
Access-Control-Allow-Headers:Content-Type,Content-Length,Authorization,If-Match,If-None-Match,X-Experience-API-Version, Accept-Language
Access-Control-Allow-Methods:HEAD, POST, GET, OPTIONS, DELETE, PUT
Access-Control-Allow-Origin:*
Access-Control-Expose-Headers:ETag,Last-Modified,Cache-Control,Content-Type,Content-Length,WWW-Authenticate,X-Experience-API-Version, Accept-Language
Connection:keep-alive
Content-Type:text/html; charset=utf-8
Date:Wed, 09 Dec 2015 19:07:25 GMT
Transfer-Encoding:chunked
WWW-Authenticate:Basic realm="ADLLRS"
X-Experience-API-Version:1.0.2
X-Frame-Options:SAMEORIGIN
**Request Headers**
Accept:_/_
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.8,es;q=0.6
Authorization:Basic+eGFwaS10b29sczp4YXBpLXRvb2xz
Cache-Control:no-cache
Connection:keep-alive
Content-Length:541
Content-Type:application/json
Host:lrs.adlnet.gov
Origin:http://localhost:8888
Pragma:no-cache
Referer:http://localhost:8888/moodle30/pluginfile.php/62/mod_tincanlaunch/content/v10.htm?endpoint=https%3A%2F%2Flrs.adlnet.gov%2Fxapi%2F&auth=Basic+eGFwaS10b29sczp4YXBpLXRvb2xz&actor=%7B%22objectType%22%3A%22Agent%22%2C%22name%22%3A%22Test+lastname%22%2C%22mbox%22%3A%22mailto%3Atest%40localhost.com%22%7D&registration=8438ae37-02b7-4d89-9e13-9479ddad3f5b
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36
X-Experience-API-Version:1.0.1
**Payload**

> [{"id":"b67f4cd0-7972-4e37-b847-74af54cde1ac","timestamp":"2015-12-09T19:18:11.635Z","actor":{"objectType":"Agent","mbox":"mailto:test@localhost.com","name":"Test+lastname"},"verb":{"id":"http://adlnet.gov/expapi/verbs/attempted","display":{"und":"attempted"}},"result":{"score":{"raw":0,"min":0,"max":0}},"context":{"registration":"8438ae37-02b7-4d89-9e13-9479ddad3f5b"},"object":{"id":"http://Course_ID1","objectType":"Activity","definition":{"name":{"en-US":"Captivate E-Learning Course"},"description":{"en-US":"Course Description."}}}}]

**Comment by garemoko** [comment]
Thanks for providing that. I think I figured this out. 

TinCanJS version 0.33.0 was released on March 3rd 2015. This included improved URL parsing and specifically [handling the addition symbol](https://github.com/RusticiSoftware/TinCanJS/blame/master/src/Utils.js#L263). 

I'm not sure which version of Captivate you're using, but even Captivate 9 which released in August 2015 may have been too far along in production to get that March update. Certainly earlier versions of Captivate did not have the update. 

So, you can fix the issue by replacing TinCanJS in your Captivate package with the most up to date version. Given that "%20" whilst technically not right does not cause any problems that I'm aware of though, I'm going to leave this plugin using that for the next release for the sake of compatibility with content using old versions of TinCanJS. 

Thanks again for reporting. If you don't mind, could you try replacing TinCanJS and not updating the plugin just to confirm my theory? Thanks!

**Comment by BatteryAcid** [comment]
I have Captivate 9.0.0.223, I have a fresh download from about two weeks ago.
I don't see a TinCanJS file in the zip but I think Captivate calls it scormdriver.js - do you know if that's the case?

**Comment by BatteryAcid** [comment]
It looks like scormdriver.js contains the entire source of tincan.js - I'm trying to replace this chunk of code with the newest but now after I re-zip the edited files the plugin is telling me "A tincan.xml file was found but it was not in the root of your zip file, please re-package your course".  Do you know how to get around this?

**Comment by garemoko** [comment]
Probably when you re-zipped it you re-zipped the folder so that the tincan.xml is 1 level up. Try zipping the contents of the folder instead. 

If it's a big hassle, don't worry about it.

**Comment by BatteryAcid** [comment]
Yea I zipped the top level folder... my bad.

Ok, I replaced the TinCanJs code with the newest and did NOT update the plugin with the PHP_QUERY_RFC3986 fix and it appears to be authenticating successfully.

Looks like your theory is confirmed.

I'm not sure where to go from here though - should I pull both of your above changes in?  Or should I keep publishing with the newest TinCanJs?

thanks for the help.

**Comment by garemoko** [comment]
Thanks for confirming that - it's good to know in case the same issue comes up anywhere else. 

Do whatever is easiest for you. I assume that's pulling my changes in from master. 

The TinCanJS change won't fix the actor thing anyway and I'll include both changes in the next release to Moodle plugin library. I'll likely leave that a week or so just in case anything else comes up. 

There may be some other benefits of using the latest TinCanJS in Captivate, maybe some improved browser compatibility or something, but I'm not aware of anything specific.
