### ISSUE TITLE
Actor object is empty

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-mod_tincanlaunch#82]
Originally raised by @BatteryAcid in #81 

The next problem (maybe this should be a separate issue) is that the Inverse Function Identifier (mbox) is not sent in any request.  As a test I just manually added it to the "actor" query param like so: 

> actor={"objectType":"Agent","mbox":"mailto:test@test.com"}

With these two changes everything went smoothly.  Is this a configuration issue or am I completely missing something.

thanks,
Bruce

**Comment by garemoko** [comment]
Replicated on localhost. Not sure how this got through my testing.

**Comment by garemoko** [comment]
The problem is on line 156 of localib.php - it's not been updated to reflect the inclusion of TinCanPHP

**Comment by garemoko** [comment]
Fixed in https://github.com/garemoko/moodle-mod_tincanlaunch/commit/c4e39d08996e831e25095d3a69a7c3229173b169. Will be in next release. 

@BatteryAcid, please can you test to confirm the fix?

**Comment by BatteryAcid** [comment]
I confirmed that it works with this fix.  
thanks!

**Comment by garemoko** [comment]
Thanks!
