### ISSUE TITLE
"Exception - Illegal value passed (no array or string given) " 

### ISSUE THREAD

**Issue by cmarif18** [davidpesce/moodle-mod_tincanlaunch#83]
Hi ,
I had installed tincan api launcher in moodle 3.0.0 version. After updating the moodle database I found this error "Exception - Illegal value passed (no array or string given) "
screenshots are provided below.
![moodle 3](https://cloud.githubusercontent.com/assets/16570506/12135416/52be81b6-b461-11e5-8bf4-c921aeadaf73.JPG)
![moodle error](https://cloud.githubusercontent.com/assets/16570506/12135417/52bf1856-b461-11e5-9681-40d3c872b129.JPG)
![moodle install validate](https://cloud.githubusercontent.com/assets/16570506/12135418/52c16976-b461-11e5-8f71-e6cbd86d59dc.JPG)
![moodle](https://cloud.githubusercontent.com/assets/16570506/12135419/52c55fe0-b461-11e5-87ea-b4b928613e2c.JPG)

Thanks,
Arif

Exception - Illegal value passed (no array or string given) " while I open the moodle url.

**Comment by garemoko** [comment]
Thanks for reporting this Arif. I'll try and make some time to test this myself either later this week or next week. 

One thing I can suggest: can you try installing by uploading the module directly to your server instead of using Moodle's zip upload? Also, have you set developer errors to maximum? If not, please do that and send me an updated screenshot. The error shown there is very vague and will be very difficult for me to do anything with unless I hit the exact same problem on my Moodle install.

**Comment by cmarif18** [comment]
Hi Garemoko,
I installed by uploading the module directly to server instead of using Moodle's zip upload.After running the cron job I got following error.
![moodle 4](https://cloud.githubusercontent.com/assets/16570506/12163968/be151b88-b537-11e5-8e64-0fdc2d517f21.JPG)

could you please told me how to set developer errors to maximum ?
Thanks,
Arif

**Comment by garemoko** [comment]
https://docs.moodle.org/30/en/Debugging

**Comment by cmarif18** [comment]
Hi Garemoko,
I had set the developer errors to maximum using the following code still got the same error.
ini_set ('display_errors', 'on');
ini_set ('log_errors', 'on');
ini_set ('display_startup_errors', 'on');
ini_set ('error_reporting', E_ALL);

Thanks, 
Arif

**Comment by garemoko** [comment]
Hi Arif, 
I don't know what that code does. Please can you try setting the errors in the interface as described in the first line of the help document I linked? Unless I can get a more specific error I don't think I can help you. 

Andrew

**Comment by cmarif18** [comment]
Hi Garemo,
I find the following notices after uploading the zip file for plugin installation 

Notice: Plugin mod_tincanlaunch does not declare valid $plugin->component in its version.php.•line 328 of /lib/classes/plugin_manager.php: call to debugging()
•line 348 of /lib/classes/plugin_manager.php: call to core_plugin_manager->load_present_plugins()
•line 217 of /lib/classes/plugininfo/base.php: call to core_plugin_manager->get_present_plugins()
•line 143 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base->load_disk_version()
•line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
•line 408 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
•line 368 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
•line 1131 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins()
•line 1112 of /admin/renderer.php: call to core_plugin_manager->missing_dependencies()
• in /home/strategi/public_html/brainballs/lib/weblib.php on line 2931

Notice: Invalid get_string() identifier: 'modulename' or component 'mod_tincanlaunch'. Perhaps you are missing $string['modulename'] = ''; in mod/tincanlaunch/lang/en/tincanlaunch.php?◦line 349 of /lib/classes/string_manager_standard.php: call to debugging()
◦line 6675 of /lib/moodlelib.php: call to core_string_manager_standard->get_string()
◦line 64 of /lib/classes/plugininfo/mod.php: call to get_string()
◦line 142 of /lib/classes/plugininfo/base.php: call to core\plugininfo\mod->init_display_name()
◦line 97 of /lib/classes/plugininfo/base.php: call to core\plugininfo\base::make_plugin_instance()
◦line 408 of /lib/classes/plugin_manager.php: call to core\plugininfo\base::get_plugins()
◦line 368 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins_of_type()
◦line 1131 of /lib/classes/plugin_manager.php: call to core_plugin_manager->get_plugins()
◦line 1112 of /admin/renderer.php: call t in /home/strategi/public_html/brainballs/lib/weblib.php on line 2931

Coding error detected, it must be fixed by a programmer: Unknown plugin type: assignfeedback

More information about this error

Debug info: 
Error code: codingerror

Stack trace: ◾line 1606 of /lib/classes/plugin_manager.php: coding_exception thrown
◾line 962 of /lib/classes/plugin_manager.php: call to core_plugin_manager->is_plugintype_writable()
◾line 1011 of /lib/classes/plugin_manager.php: call to core_plugin_manager->is_remote_plugin_installable()
◾line 1169 of /admin/renderer.php: call to core_plugin_manager->filter_installable()
◾line 212 of /admin/renderer.php: call to core_admin_renderer->missing_dependencies()
◾line 662 of /admin/index.php: call to core_admin_renderer->upgrade_plugin_check_page()

Thanks,
Arif

**Comment by garemoko** [comment]
That's weird. Can you check that the version.php file for the module matches the one here? https://github.com/garemoko/moodle-mod_tincanlaunch/blob/master/version.php 

As you can see, it **does** declare $plugin->component. Did you definitely get the right version of the plugin?

**Comment by garemoko** [comment]
Assuming this was caused by using the wrong version of the plugin. Please re-open if that's not the case.
