### ISSUE TITLE
Issue plugin tincan

### ISSUE THREAD

**Issue by delagarzaluciano** [davidpesce/moodle-mod_tincanlaunch#84]
I have next:
- moodle version 3.0 (Build: 20151116)  
- tincan api launch link Release 1.2RC3 (Build: 2015121100)
- cloud scorm account

i have installed in  http://ifnmx123.esy.es/TinCan/ and the track is good with this tool,  but in moodle throw the next error

Fatal error: Class 'TinCan\statement' not found in /opt/bitnami/apps/moodle/htdocs/mod/tincanlaunch/locallib.php on line 69

**Comment by garemoko** [comment]
Hi. It sounds like you are missing TinCanPHP. 

Please install the **latest** version from the plugins library: https://moodle.org/plugins/mod_tincanlaunch

**Comment by delagarzaluciano** [comment]
i downloaded the ultimate version  mod_tincanlaunch_moodle30_2015121100.zip and i installed the plugin from "zip".

**Comment by garemoko** [comment]
Does the file have a TinCanPHP folder in it with files in that?

**Comment by delagarzaluciano** [comment]
![tincan](https://cloud.githubusercontent.com/assets/16650278/12461714/0017256a-bf80-11e5-91c7-dd6044aa56bd.png)

Yes,  the files show in the image

**Comment by delagarzaluciano** [comment]
the next configuration 

moodle 3.0+ (Build: 20151204)
plugin tincan api launch link  1.2RC3 (Build: 2015121100)

locally, works fine the tracking.....

I will try locally the firts configuration...... with  moodle version 3.0 (Build: 20151116)

**Comment by delagarzaluciano** [comment]
Andrew my problem is solved, i explain the solution.
In the folder TincanPHP/src the archive is Statement.php with the first capital letter
![aj1](https://cloud.githubusercontent.com/assets/16650278/12485237/7d456184-c023-11e5-82f7-30c0cfe24151.png)

and the scrip php en tincanlaunch/locallib.php in the line 69 is lower case "statement" only replace "s" for "S" and work fine the plugin.

![aj2](https://cloud.githubusercontent.com/assets/16650278/12485398/3edc6b1c-c024-11e5-8751-9620f5cd427a.png)

Thanks for your help 

Solved!!!!!

**Comment by garemoko** [comment]
This should be fixed in the next commit I make to master. I'm going to assume I didn't hit the error because maybe it only affects windows and not unix based servers.
