### ISSUE TITLE
Add score to Moodle gradebook

### ISSUE THREAD

**Issue by delagarzaluciano** [davidpesce/moodle-mod_tincanlaunch#85]
Hello Andrew again:

sample image of a video 
![progreso](https://cloud.githubusercontent.com/assets/16650278/12488677/5c117bec-c032-11e5-8336-a174474259fa.png)

In Moodle i dont can see the finalization checked.

is possible save the calification in moodle?

**Comment by garemoko** [comment]
Hi,
Are you using the completion settings?

**Comment by delagarzaluciano** [comment]
Yes in the course and the configuration of activity tin can

**Comment by garemoko** [comment]
can you share a screenshot of the settings in the activity please? Which verb are you using and does it match the verb sent by the course you are using?

**Comment by delagarzaluciano** [comment]
Hello Andrew:

Here is my configuration 
![confxapi](https://cloud.githubusercontent.com/assets/16650278/12514509/6681559a-c0e9-11e5-8be9-a1243051a220.jpg)

**Comment by delagarzaluciano** [comment]
ok, sorry is passed 
 http://adlnet.gov/expapi/verbs/passed

Thanks Andrew i will put more attention

**Comment by delagarzaluciano** [comment]
i can register the calification obtained  from the LRS  to Moodle?

**Comment by garemoko** [comment]
Sorry, I don't understand this word "calification". 

Good to see the translations getting some usage!

**Comment by delagarzaluciano** [comment]
i can register the score obtained from the LRS in Moodle?

like   activity in moodle for register score in the Grade book view

Maybe, the image help you understand a little

![sin titulo-1](https://cloud.githubusercontent.com/assets/16650278/12519079/360692fe-c102-11e5-8831-b15ebb29096e.jpg)

**Comment by garemoko** [comment]
@delagarzaluciano oh, I understand. 

Sorry, that's not a feature of this plugin today, but it's certainly possible with some coding work. I guess the approach would be to fetch the grade when the plugin checks for completion. The tricky bit would be figuring out which statement has the score and if multiple statements include a score, which one to use. It might need some configuration settings. 

Are you a developer or do you have access to developers? Is this something you'd like to tackle?

**Comment by hshafy** [comment]
Hello Andrew,

I have the same issue as @delagarzaluciano I made a clean installation of moodle 3.1 on AWS then installed the tincanlaunch plugin, my activity is sending the statements correctly to cloud scorm, but moodle doesn't get it back to tick the completion.

I use http://adlnet.gov/expapi/verbs/completed verb in both the settings and in the activity (I see the statement correctly in the scorm cloud), I also didn't install the "Tin Can Learner Stream" (should I?)

Did I miss something?

**Comment by garemoko** [comment]
@hshafy are you sure it's the same issue? If so, see the answer here: https://github.com/garemoko/moodle-mod_tincanlaunch/issues/85#issuecomment-174015193

It sounds like maybe you have a different issue though. If so, please can you create a separate issue?

**Comment by hshafy** [comment]
@garemoko I was talking about the first issue on the top of this thread regarding the completion tick, not th score.

**Comment by garemoko** [comment]
I see, yes it does look like the issue shifted. I guess I need to be more strict about making people create new issues. I'll create a new issue for you.

**Comment by garemoko** [comment]
Not going to develop this. PRs welcome.
