### ISSUE TITLE
LRS recommendation

### ISSUE THREAD

**Issue by nadavkav** [davidpesce/moodle-mod_tincanlaunch#9]
Hi Andrew,

I have tried to use this plugin with Jamie Smith's LRS : https://github.com/jgsmitty/Experience-API-for-Moodle
And it does not seem to work. 
I am using Jamie's LRS with the Tincan implementation/modification he made to the Moodle SCORM module. And it works fine. Though I am not sure he implemented everything, And that is way it does not work with your plugin.
Do you have any experiance with it?

Can you recommend any other LRS (free ones too)?

Regards,
Nadav :smiley:

**Comment by garemoko** [comment]
Hi, 
I'm afraid I've not tried Jamie's plugin but from what I understand it's not a full LRS. 

Both Wax LRS and SCORM Cloud are cloud based services and have free plans.

Andrew

**Comment by nadavkav** [comment]
Thanks :smiley:
