### ISSUE TITLE
Check time zone of timestamp of launched statement

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-mod_tincanlaunch#94]
Since we're not setting the timezone this is probably wrong.

**Comment by scara** [comment]
Date and time in Moodle should be UTC based: [userdate()](https://github.com/moodle/moodle/blob/0aefe91c50d4edb1051ae99d1dcd065d616571da/lib/moodlelib.php#L2167) is the function to map them into a user time zone.

**Comment by garemoko** [comment]
The statements should use UTC. The trouble is that if a server is configured with a default timezone other than UTC, I believe the statements will be wrong with the current code. I need to test but the fix should be straightforward,

**Comment by garemoko** [comment]
Turns out this bug never existed. I just set my Modoel timezone to America/Chicago and the timestamp of the statement sent was fine.
