### ISSUE TITLE
Question only: composer install

### ISSUE THREAD

**Issue by polothy** [davidpesce/moodle-mod_tincanlaunch#97]
Does one need to run `composer install` in `mod/tincanlaunch/TinCanPHP` prior to using this plugin?  Or can it be used, as is, when downloaded from https://moodle.org/plugins/mod_tincanlaunch ?

**Comment by garemoko** [comment]
You should be able to use it as-is when downloaded from the plugins directory. Any problems, please let me know in a new issue.

**Comment by polothy** [comment]
Thanks for the reply!
