### ISSUE TITLE
Completion tick not ticking when require view is enabled

### ISSUE THREAD

**Issue by garemoko** [davidpesce/moodle-mod_tincanlaunch#98]
@hshafy reports that the completion tick is not ticking in Moodle 3.1

@hshafy - please can you make sure that completion tracking is turned on, the settings are populated and that the cron is running? Then please can you send a screenshot of the completion and actor settings and an example of a statement that you think should be causing the Moodle to mark completion?

Thanks!

**Comment by hshafy** [comment]
Thank you for creating the issue @garemoko , apparently this issue is not an exception with 3.1 as we have another deployment with moodle 2.7.2 that have the same problem.

Please find the settings screenshots and the cron output in addition to the statement that we think should cause the completion

![screenshot from 2016-06-07 11 57 43](https://cloud.githubusercontent.com/assets/8539756/15854233/70b02562-2cb1-11e6-94f8-488bc246e2a3.jpg)
![screenshot from 2016-06-07 11 59 14](https://cloud.githubusercontent.com/assets/8539756/15854232/70afe07a-2cb1-11e6-821b-30557882178f.jpg)
![screenshot from 2016-06-07 12 14 19](https://cloud.githubusercontent.com/assets/8539756/15854338/ff44e57e-2cb1-11e6-89ce-03805414d3e1.jpg)

Here is the cron job output:

> Execute scheduled task: Expire credentials (mod_tincanlaunch\task\expire_credentials)
> ... started 09:53:01. Current memory use 38.5MB.
> ... used 1 dbqueries
> ... used 0.00016403198242188 seconds
> Scheduled task complete: Expire credentials (mod_tincanlaunch\task\expire_credentials)
> Cron script completed correctly
> Cron completed at 09:53:01. Memory used 38.5MB.
> Execution took 0.220284 seconds

And here is the statement that we think should cause the completion:

> Admin User completed 'http://tincanapi.com/ku_the_essentials'

{
    "id": "9d1f4520-afa5-4741-bc03-b0bddb42b905",
    "actor": {
        "name": "Admin User",
        "mbox": "mailto:hxxxxxxxxx@gmail.com",
        "objectType": "Agent"
    },
    "verb": {
        "id": "http://adlnet.gov/expapi/verbs/completed",
        "display": {
            "und": "completed"
        }
    },
    "timestamp": "2016-06-05T22:06:52.686Z",
    "stored": "2016-06-05T22:06:53.412Z",
    "authority": {
        "name": "Unnamed Account",
        "account": {
            "homePage": "http://cloud.scorm.com/",
            "name": "YpAy46k-NPwhU5j6uSg"
        },
        "objectType": "Agent"
    },
    "version": "1.0.0",
    "object": {
        "id": "http://tincanapi.com/ku_the_essentials",
        "objectType": "Activity"
    }
}

**Comment by garemoko** [comment]
@hshafy what's the activity id within launch settings?

**Comment by garemoko** [comment]
I've tested this feature on my local Moodle (3.0) and it works as expected. Hopefully you have the activity id wrong, otherwise I'm out of ideas :-)

**Comment by hshafy** [comment]
@garemoko here it's is!

I think it's correct !

![screenshot from 2016-06-07 12 26 58](https://cloud.githubusercontent.com/assets/8539756/15854672/cce4f2d4-2cb3-11e6-8b7c-ad091184148e.jpg)

**Comment by hshafy** [comment]
@garemoko do I need to configure the LRS Integration in the LRS settings? do you notice any other issue with the configuration?

**Comment by garemoko** [comment]
@hshafy everything looks fine... perhaps we can set up a call to do a screenshare and try to puzzle this out? Can you email andrew.downes@watershedlrs.com and suggest some times? 

Also, can you try setting debug errors to maximum and see if you get any error messages?

**Comment by hshafy** [comment]
@garemoko thank you man for your time, it suddenly worked now, I don't know what did I do :) 

The only thing that I have changed before sending screenshots was to fix the cron job, it wasn't running correctly, but after it did, the problem persisted (but didn't register new completion statement at that time).

When I tried the course one more time (send new completion statement), I found it worked, probably this was the problem, I will try to check my other deployment and see if it was the same issue and get back to you.

**Comment by garemoko** [comment]
@hshafy glad it worked. I don't think cron was the problem though since on my local Moodle I don't have cron running either and it worked there. The completion check probably SHOULD be run as a cron task but isn't currently. 

Possibly the problem was that you didn't click 'return to course' or you didn't wait long enough after the statement was issued before navigating away from the launch page (or you navigated away BEFORE the statement was sent).

**Comment by hshafy** [comment]
@garemoko is it required to click on the "return to course" I tried it without clicking on it now and it works fine!

I really don't know what was the issue or how it was fixed, I will wait tell I get a confirmation from the other installation admin and see, maybe it was a wrong configuration.

but thank you for your time and your efforts, no plans in the near future to integrate more statements into moodle? like scores and so on?

**Comment by garemoko** [comment]
For now, there are no plans to integrate scores into the gradebook. Pull requests are welcome!

**Comment by hshafy** [comment]
Hello @garemoko  Now I know what was happened, see attached, here in the configuration, the "Require View" when ticked the completion doesn't work, when unticked it works, keeping all other configurations the same, this doesn't make sense to me, do you know why?

![screenshot from 2016-06-08 10 46 18](https://cloud.githubusercontent.com/assets/8539756/15888521/e91557ca-2d6f-11e6-8a07-6333fdff1b6b.jpg)

**Comment by garemoko** [comment]
@hshafy I think this is a new feature that's not been accounted for in the code. Ticking this presumably means that the learner has to both view the item and have the relevant verb and I guess we're not recording item views anywhere.

**Comment by hshafy** [comment]
@garemoko ok, now clear, thank you.

**Comment by garemoko** [comment]
Took a little look at this and I can't even see where that setting is getting recorded in the database. Seems like a bigger task than I thought so leaving this for now.

**Comment by garemoko** [comment]
Can be fixed following the instructions here: https://docs.moodle.org/dev/Activity_completion_API#Completion_on_view

Should be in the next feature release.

**Comment by garemoko** [comment]
Addressed in https://github.com/garemoko/moodle-mod_tincanlaunch/tree/completion-features needs testing.

**Comment by garemoko** [comment]
Assuming the completion features branch got merged.
