### ISSUE TITLE
Error after installing TinCan 

### ISSUE THREAD

**Issue by kelvinsleonardo** [davidpesce/moodle-mod_tincanlaunch#99]
**After upload plugin, this error was generated**

![captura_de_tela](https://cloud.githubusercontent.com/assets/7854286/16012786/4fd5ef34-3161-11e6-82b4-64eba07e5022.png)

I have tried in version '3.0.2+ (Build: 20160129)' and '3.1+ (Build: 20160609)' of the moodle.

**Comment by garemoko** [comment]
@kelvinsleonardo thanks for flagging this. It looks like maybe the folder structure is wrong in the zip or something. can you make sure you have the latest version from the Moodle plugins directory and then go to the mod folder in your Moodle installation and tell me what you see?

**Comment by kelvinsleonardo** [comment]
@garemoko 

![captura_de_tela-1](https://cloud.githubusercontent.com/assets/7854286/16013539/375deb3e-3164-11e6-8d09-8bd5867c820c.png)

I have tried in version '3.0.2+ (Build: 20160129)' and '3.1+ (Build: 20160609)' of the moodle.

**Comment by garemoko** [comment]
Thx. And immediately inside the tincanlaunch folder, does it have a file called version.php (and lots of other files), or another folder? If it has another folder, make sure it's called "tincanlaunch" and move it directly to the mod folder. 

Please let me know if that fixes it or not.

**Comment by kelvinsleonardo** [comment]
In the mod folder have two folders "moodle-mod_tincanlaunch-master" and "tincanlaunch" , follows bellow:

![primeirapasta](https://cloud.githubusercontent.com/assets/7854286/16016330/ec50bee8-3170-11e6-886b-d6dd4cde3827.png)

![segundapasta](https://cloud.githubusercontent.com/assets/7854286/16016337/f3fd382e-3170-11e6-9bf0-92eae3ff140e.png)

**Comment by garemoko** [comment]
Oh. Delete moodle-mod_tincanlaunch-master for sure. Did you try and install the version from github earlier in the process?

**Comment by garemoko** [comment]
In fact,the contents of tincanlaunch are totally wrong too. When you open up the version.php there does it say anything interesting?

**Comment by kelvinsleonardo** [comment]
I opened "version.php" in file "tincanlauch".

![version](https://cloud.githubusercontent.com/assets/7854286/16016980/1d6fe65e-3174-11e6-8c80-ba09fb960aca.png)

**Comment by garemoko** [comment]
I have no idea how it happened, but it looks like the "assignment" folder got renamed to tincanlaunch. I recommend renaming the folder and maybe asking for help on the Moodle forums if it happens again when you reinstall the plugin. 

If you didn't already delete moodle-mod_tincanlaunch-master  you could rename that tincanlaunch and it might just work.

**Comment by kelvinsleonardo** [comment]
Problem solved, i reinstalled the moodle. Before, followed this tutorial
https://www.youtube.com/watch?v=qJxO4Ene2kM and had downloaded in https://github.com/garemoko/moodle-mod_tincanlaunch .zip in the wrong place, now, i downloaded in https://moodle.org/plugins/mod_tincanlaunch and worked. Sorry about the happen.

**Comment by garemoko** [comment]
Great. Thanks!
